Feature/eicnet group wiki detailed rework
EIC-EA/EIC-community-D8 pull request #1001
Opened 2021-12-16 10:20 UTC by Askerx9

### What I did

- [ ] nav list is expended by default
- [ ] On mobile the sidebar menu should be expanded vertically

### What I need

- [ ] Management buttons are not on the same line
- [ ] Missing request delete and archival action in the manage button
- [ ] The wording of the buttons is incorrect
- [ ] Add extra class on navigation list container to remove the padding on mobile (.ecl-editorial-article__aside)

2021-12-16 10:55 UTC, lenglebert commented
Back-end work needs to be done: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1871

2021-12-21 14:28 UTC, filipvt1 requested changes
On mobile there still seems to be some extra padding being added to the ".ecl-editorial-article__aside" item. Check why this padding is there and if not necessary, remove it. Otherwise overwrite it for the wiki page.

2021-12-21 14:28 UTC, filipvt1 commented on lib/themes/eic_community/js/components/drupal.navigation-list.js
>      if (readSession('collapsed')) {
What is the definition of "expanded by default"? Does this mean that on every page load it is expanded again? In that case, what's the point of storing it in the session? If it is on the initial pageload then I think this implementation isn't correct. Because now it is forcing it to be expanded every time you reload the page or you move to another page.

2021-12-22 13:58 UTC, filipvt1 approved these changes

2022-01-03 08:10 UTC, merged