Feature/eicnet 1860 data export 2
EIC-EA/EIC-community-D8 pull request #1020
Opened 2022-01-04 14:18 UTC by lramarojaona

### Improvements

- Introduced a Group Metrics views field, which is based on GroupMetric plugins

### Tests

- [ ] Create a Group based view
- [ ] Make sure you have content for: group content, members, memberhsip requests, invitations, flags, downloads, comments inside your groups
- [ ] Add a `Group: Group Metrics` field for each of the plugins and configure them to test them as you wish: `Group flags`, `Group invitations`, `Group members`, `Group comments`, `Group downloads`, `Group membership requests`, `Group content`
- [ ] Make sure you have relevant/correct counters

2022-01-11 12:19 UTC, 4hardfire requested changes

2022-01-11 12:19 UTC, 4hardfire commented on lib/modules/eic_groups/eic_groups.module
> +  ];
@lramarojaona why do we have the same implementation in `eic_group_statistics.module`?

2022-01-11 12:22 UTC, 4hardfire commented
@lramarojaona the group contributors always show 0. I don't know if this is an issue or not. Is there a way I can test it?

2022-01-11 14:24 UTC, lramarojaona commented on lib/modules/eic_groups/eic_groups.module
> +  ];
Oh sorry indeed, you're right, this is a leftover, just removed it.

2022-01-11 14:27 UTC, lramarojaona commented
> @lramarojaona the group contributors always show 0. I don't know if this is an issue or not. Is there a way I can test it?



> @lramarojaona the group contributors always show 0. I don't know if this is an issue or not. Is there a way I can test it?

This counter should show active members that own published nodes. Do you have that?

2022-01-14 15:56 UTC, 4hardfire requested changes
Group contributors keeps showing 0 even though I created new content in a published group as TU.

2022-01-17 13:31 UTC, merged