[DRAFT] [EICNET-1929] wiki pages front end
EIC-EA/EIC-community-D8 pull request #1055
Opened 2022-01-13 16:58 UTC by Askerx9

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1929&quickFilter=26820&quickFilter=26822

### What I did

- [ ] You can fold open the wiki nav menu, but you cannot close it.
- [ ] When you close the dropdown of multiple indents in wiki pages, it gets an active yellow state.
- [ ] have trouble knowing in what wiki page I am, there is no active state on the links.
- [ ] Adding an image is currently breaking the styling
- [ ] When you navigate through pages on mobile it always jumps to the top. 
- [ ] Indenting is not visually aligned with design, leave space left the more you indent
- [ ] When not logged in I have overlapping content on wiki pages, block for anonymous users to login is shown on top of the wiki pages.

### Remarks

_have trouble knowing in what wiki page I am, there is no active state on the links._

> BE, is it possible to send me something to know which page is the current page and send me a title in the content please

2022-02-01 10:38 UTC, filipvt1 requested changes
When you have multiple nested items active, it looks a bit strange when all the grey boxes are connected. Maybe we should add a very small margin on ".ecl-navigation-list__link". In the design there is also a difference between the top active state and the nested active state.
![image](https://user-images.githubusercontent.com/86473669/151952220-95f65a08-9be4-4b81-ae23-193884660319.png)

The "flex-wrap: wrap" on the ".ecl-editorial-article--is-collapsible .ecl-editorial-article__wrapper" element is causing issues when you place an image inside the content. This causes the content to drop below the navigation. I think that with the addition of the "ecl-editorial-article__container--wiki" that property isn't necessary anymore, please check this. If you remove the wrap, you will have to move the login container inside the "ecl-editorial-article__container--wiki" container.

The images added in the body of a wiki page have a height attribute, so you need to set "height: auto" in css otherwise they will because distorted when the "max-width:100%" declaration kicks in.

2022-02-01 10:38 UTC, filipvt1 commented on lib/themes/eic_community/patterns/components/navigation-list/navigation-list-items.html.twig
> +          <a  href="{{ item.link.path }}{{ anchor }}">
You also need to pass this anchor along to the nested level at line 29. Because it currently only works on the first level.

2022-02-02 15:28 UTC, filipvt1 requested changes
Image height is still an issue, they are being stretched.
It might be best to place the login container inside the "ecl-editorial-article__content--wiki" container. You will have to apply some additional styling because the login container has an "ecl-container" inside it that sets some fixed widths which will push the content outside of the container.

2022-02-04 17:39 UTC, 4hardfire commented on lib/themes/eic_community/includes/preprocess/blocks/block--eic-groups-wiki-book-navigation.inc
> -      if (is_int(strpos($path_alias, $link_item['url']->toString()))) {
@filipvt1 This should be ok now. Can you validate?

2022-02-15 10:29 UTC, merged