EICNET-1858: Group ownership transfer confirmation improvements
EIC-EA/EIC-community-D8 pull request #1096
Opened 2022-01-25 08:23 UTC by 4hardfire

### Improvements

- Change request timeout field to a select list with options.
- Add request expiration date in message notification.
- Show request expiration date in group admin members overview.

### Todo

- [ ] EICNET-1930: GO transfer request confirmation (accept or deny) should be allowed only for the targeted user

### Tests

- [ ] As GO, go to a group members page `/groups/<group-name>/members`
- [ ] Request ownership transfer to a GA and make sure the timeout field is a select list
- [ ] Click on request transfer ownership to create the request
- [ ] Go back to the group members page and check if the expiration date is shown in the list bellow the GA that got requested
- [ ] As SA, run cron
- [ ] Check if the new GA receives a notification and the expiration date is presented

2022-02-01 11:06 UTC, lramarojaona requested changes

2022-02-01 11:06 UTC, lramarojaona commented on lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
> +    $access = AccessResult::forbidden();
Ok, sorry, this is an abstract class

2022-02-01 11:06 UTC, lramarojaona commented on lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
> +    $expiration_date = 0;
Maybe add a comment that the feature is designed to have one open request at a time only?

2022-02-02 08:25 UTC, 4hardfire commented on lib/modules/eic_flags/src/Form/RequestCancelForm.php
> +      throw new InvalidArgumentException('Flag doesn\'t exists');
Done!

2022-02-02 08:25 UTC, 4hardfire commented on lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php
> +    $expiration_date = 0;
Done!

2022-02-02 09:05 UTC, 4hardfire commented on lib/modules/eic_flags/src/Form/RequestCancelForm.php
> +      $container->get('datetime.time'),
Done!

2022-02-03 09:32 UTC, lramarojaona approved these changes

2022-02-03 12:23 UTC, merged