[DRAFT] [EICNET-1782] rework design of ecl-teaser story
EIC-EA/EIC-community-D8 pull request #1099
Opened 2022-01-25 10:40 UTC by Askerx9

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1782&quickFilter=26826

### What I did

[ ] - We miss a <hr> between the different news articles
[ ] - The upper news article sticks on the upper <hr>
[ ] - Date (time) should be aligned to the right
[ ] - Statistics currently do not get updated
[ ] - Not sure on this one, but on organisation detail we have the introduction listed as content below title, on the organisation news overview we have description listed.
[ ] - Thumbnail should be cropped automaticly to be consistent on the page.

2022-01-26 10:06 UTC, 4hardfire requested changes

2022-01-26 10:06 UTC, 4hardfire commented on lib/modules/eic_search/eic_search.services.yml
> +    arguments: ['@database', '@flag.count', '@search_api.post_request_indexing', '@eic_statistics.statistics.storage.node.decorator', '@eic_comments.helper', '@eic_media_statistics.entity_file_downlo
@Dromadoros some arguments should be removed since we moved the logic to different services.

2022-01-26 10:21 UTC, 4hardfire commented on lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
> +    }
@Dromadoros is there a reason why this part is duplicated from the method `supports`?

2022-01-26 10:49 UTC, 4hardfire requested changes
@Dromadoros For some reason after a fresh install, when I go to the groups overview page all the groups (public/private/restricted) are showing "Public" in the visibility label. Also when I logout, I still see private groups as anonymous (even though I cannot access the group detail page). Could you have a look?

2022-01-26 14:17 UTC, filipvt1 commented
Front-end OK

2022-01-27 09:03 UTC, 4hardfire commented
> @Dromadoros For some reason after a fresh install, when I go to the groups overview page all the groups (public/private/restricted) are showing "Public" in the visibility label. Also when I logout, I still see private groups as anonymous (even though I cannot access the group detail page). Could you have a look?

Seems fixed!

2022-01-27 09:03 UTC, 4hardfire approved these changes
BE changes seem ok to me!

2022-02-15 10:37 UTC, merged