EICNET-2063: As non logged in user looking at a wiki page gives CTA which overlaps with the wiki itself
EIC-EA/EIC-community-D8 pull request #1143
Opened 2022-02-09 13:18 UTC by 4hardfire

### Changes

- Hide login block from wiki pages.

### Tests

- [x] As anonymous user, go to a wiki page of a public group
- [x] Make sure the login block (with text: "Please login to see comments and contribute") is hidden from the page since we don't currently use comments in wiki pages

### Remarks from QA to validate with PMs

- Currently we do not have comments on wiki pages, should the CTA show different copy for this?

FA: https://citnet.tech.ec.europa.eu/CITnet/confluence/display/EICNET/CT+-+Wiki+page#CTWikipage-Commentable

- This suggests we should also activate comments on wiki pages?

2022-02-10 09:42 UTC, lramarojaona requested changes

2022-02-10 09:42 UTC, lramarojaona commented on lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
> +    switch ($node->bundle()) {
I think we should just remove the field_comments if we don't use it.
In that way, the day we want comments for wiki pages, we just need to add the field and avoid exceptions

2022-02-15 09:22 UTC, 4hardfire commented on lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
> +    switch ($node->bundle()) {
Indeed. I will remove the field for now.

2022-02-15 09:27 UTC, 4hardfire commented on lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
> +    switch ($node->bundle()) {
Done!

2022-02-15 09:50 UTC, lramarojaona approved these changes

2022-02-15 12:15 UTC, merged