[EICNET-2081] my notifications management
EIC-EA/EIC-community-D8 pull request #1147
Opened 2022-02-11 15:16 UTC by Askerx9

### What I did

- [ ] toggle checkbox
- [ ] My settings layout
- [ ] My setting/notifications in twig
- [ ] My setting/notifications in React

### Toggle checkbox

- http://localhost:8080/themes/custom/eic_community/storybook-static/?path=/story/components-toogle-switch--base
> Now we have a component that we can reuse in some Forms

### My settings layout
- StoryBook: http://localhost:8080/themes/custom/eic_community/storybook-static/?path=/story/bundles-member-my-settings--email-notifications
- Layout: https://www.figma.com/file/j583oU3vO3YfrU3SnZp4vQ/EIC---Analysis?node-id=335%3A11398

### My setting/notifications in twig
- StoryBook: http://localhost:8080/themes/custom/eic_community/storybook-static/?path=/story/compositions-notifications-management-line--base
- Layout: https://www.figma.com/file/j583oU3vO3YfrU3SnZp4vQ/EIC---Analysis?node-id=374%3A14153

**Remarks**
> this is a static view (no collapse) because everything is done in React part

### My setting/notifications in React
- Layout: https://www.figma.com/file/j583oU3vO3YfrU3SnZp4vQ/EIC---Analysis?node-id=374%3A14153

> to test, put this code in html.html.twig
`   
 {{ attach_library('eic_community/react-notif-management') }}
    <div id="notif-management-overview"></div>
`

### What To be need ?

- [ ] add all call API to switch the state of notifications
- [ ] add empty state in React components

2022-02-23 13:54 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/Toggle/entrypoint.js
> +import Toggle from "./index";
I think the empty line should be below the import Toggle

2022-02-23 13:55 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/NotifManagement/index.js
> +    console.log('navigate to page', page);
Do we need this on environments?

2022-02-23 13:58 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/NotifManagement/index.js
> +      resultsPerPage: 10,
isn't it better to receive this value from the back-end? Like Overviews we have

2022-02-23 14:00 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/NotifManagement/components/RowNotif.js
> +          <Row translations={this.props.translations} parentIndex={this.props.rowIndex} row={this.props.row}
Can we maybe indent this better, props line by line? just for readability

2022-02-25 16:03 UTC, filipvt1 commented on lib/themes/eic_community/react/components/Block/NotifManagement/index.js
> +      resultsPerPage: 10,
yes, when we implement the backend endpoint these values should definitely come from the backend. The fixed total was added for test/demo purposes to show the pagination.

2022-02-25 16:04 UTC, filipvt1 commented on lib/themes/eic_community/react/components/Block/NotifManagement/index.js
> +    console.log('navigate to page', page);
you mean the console.log? No that should be removed. But we do still need to implement the pagination mechanism here.

2022-03-04 10:23 UTC, lramarojaona requested changes
It's working, but I have some comments.

Also we need a followup ticket to handle notification frequency, I'll chekc with Lucas

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/src/NotificationFrequencies.php
> +namespace Drupal\eic_user;
Wouldn't it be better to move this into `eic_message_subscriptions` module?

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/eic_user.services.yml
> +  eic_user.notification_settings_manager:
Wouldn't it be better to move this into `eic_message_subscriptions` module?

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/src/Controller/MySettingsController.php
> +    return [];
Is this a required function?

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/src/Controller/MySettingsController.php
> +    $body = json_decode($request->getContent(), TRUE);
I usually use this https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Serialization%21Json.php/function/Json%3A%3Adecode/9.3.x

But it does the same I agree

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/src/Plugin/Block/NotificationsSettingsBlock.php
> +            'no_results_body' => $this->t('Could not find any results.'),
Is there a reason not use https://www.drupal.org/docs/8/api/translation-api/overview#s-context-in-drupalt-and-drupalformatplural ?

React maybe?

2022-03-04 10:23 UTC, lramarojaona commented on lib/modules/eic_user/src/Service/NotificationSettingsManager.php
> +      throw new \InvalidArgumentException('Current user doesn\'t exist');
Drupal coding standards recommend `("Current user doesn't exist")` in this case

2022-03-04 15:49 UTC, korhankale commented on lib/modules/eic_user/src/NotificationFrequencies.php
> +namespace Drupal\eic_user;
Already agreed on the way we'll split this

2022-03-04 15:50 UTC, korhankale commented on lib/modules/eic_user/src/Controller/MySettingsController.php
> +    $body = json_decode($request->getContent(), TRUE);
Indeed it does the same thing (json_decode as array)

2022-03-04 15:52 UTC, korhankale commented on lib/modules/eic_user/src/Controller/MySettingsController.php
> +    return [];
Yes in the routing definition it is required that the function exists

2022-03-04 15:53 UTC, merged