EICNET-1728: Group invite users in bulk (improvements)
EIC-EA/EIC-community-D8 pull request #1149
Opened 2022-02-14 14:19 UTC by 4hardfire

### Improvements

- Create new access check to control if user can access group invite bulk routes.
- Replace invite user in group header with bulk invite user.
- Allow GMs to invite multiple users.
- Redirect users to the group homepage after inviting a user.

### Tests

NEW: the old link "Invite user" in the group header should now be "Invite users" and it should redirect the user to the form to invite multiple users. Previously the link to invite multiple users was located in the group management dropdown and it was removed.

- [x] ~~As GO/GA, make sure you can only invite multiple users when the group is in DRAFT or PUBLIC state~~.
- [x] ~~As GM, make sure you cannot invite multiple users (this is a feature for GO/GA only)~~
- [x] As SA/SCM edit the group, enable the option "Invite members" and make sure the group is published
- [x] As GM, make sure you can invite multiple users via the link "Invite users" in the group header
- [x] As GM, try to invite multiple users and make sure you get redirected to the group homepage afterwards
- [x] As SA/SCM edit the group and disable the option "Invite members"
- [x] As GM, make sure you cannot invite multiple users via the link "Invite users" in the group header
- [x] As GO/GA, make sure you can still invite members
- [x] As SA/SCM, try to change the group status to PENDING, BLOCKED and ARCHIVED and make sure GO/GA cannot invite members

### Questions

- Should we take into account if the checkbox "Invite members" is checked before allowing GO/GA to be able to invite multiple users?

> Answer from PM: Invite multiple users is avail for SA, SCM, GO, GAs by default. It's also available for a GM in case the checkbox "GMs can invite other GMs" in the group management screen is checked. We now have 2 invite feature for a group. We should replace the "invite user" functionality (which only allows you to invite a single user) with the "multiple invite user" functionality.

2022-02-15 10:36 UTC, lramarojaona requested changes

2022-02-15 13:25 UTC, 4hardfire commented on lib/modules/eic_groups/src/Access/GroupInvitationBulkAccessChecker.php
> +    // @todo In the future we should include the archived state after
Done. Note that I also had to apply the same logic for the **Invite user** action (not the invite multiple members).

2022-02-15 13:26 UTC, lramarojaona approved these changes

2022-02-17 11:39 UTC, lramarojaona commented
@4hardfire , Everything works although I can't change the group state to "Blocked" while besing SA, this is strange :/

2022-02-17 11:40 UTC, lramarojaona approved these changes

2022-02-17 12:31 UTC, merged