[EICNET-1782]feat: Set introduction field in teaser of search news
EIC-EA/EIC-community-D8 pull request #1153
Opened 2022-02-15 13:09 UTC by Dromadoros

How to test:

- [x] Re-index everything
- [x] Go to organisation detail in News overview
- [x] check that the description in the teaser is the field "introduction"

2022-02-15 14:04 UTC, lramarojaona requested changes

2022-02-15 14:04 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
> +          <div className="ecl-teaser__description" dangerouslySetInnerHTML={{__html: props.result.ss_content_introduction_string.replace(/(<([^>]+)>)/gi, "")}} />
You should use the `HTML filter` processor provided by Search API ( we need to check if all text fields are applicable or if we should exclude some of them).
This way we strip tags only on index process and not on each display in the browser.

2022-02-15 14:05 UTC, lramarojaona commented
@Dromadoros , also in organisation news, I see both the Introduction and the body displayed in the overview list I guess it should be introduction only?

2022-02-22 10:36 UTC, Dromadoros commented
> @Dromadoros , also in organisation news, I see both the Introduction and the body displayed in the overview list I guess it should be introduction only?

I think you need to clean all data in solr and re-index it, it doesn't take anymore the basic render of news type

2022-02-22 10:37 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js
> +          <div className="ecl-teaser__description" dangerouslySetInnerHTML={{__html: props.result.ss_content_introduction_string.replace(/(<([^>]+)>)/gi, "")}} />
> You should use the `HTML filter` processor provided by Search API ( we need to check if all text fields are applicable or if we should exclude some of them). This way we strip tags only on index process and not on each display in the browser.

It's a good idea but fulltext is used a lot of times and I'm scared that it will break some stuff on some components. So for performance wised like you said I removed on the front itself and added it on the index process. So when we will load the overview it will not apply the striptag function one by one anymore

2022-02-23 09:51 UTC, lramarojaona approved these changes

2022-02-24 10:11 UTC, merged