EICNET-2114: Fix permission tab in Event about page
EIC-EA/EIC-community-D8 pull request #1192
Opened 2022-02-24 12:53 UTC by 4hardfire

### Fixes

- Show custom restricted options (restricted users + restricted organisations + restricted organisation types) when viewing Group/Event about page.

### Tests

- [ ] Add or edit a custom restricted group and a custom restricted global event
- [ ] Enable all custom restricted options and fill in the values
- [ ] Save it
- [ ] Go to the about page of the Group and Global Event
- [ ] Make sure all custom restricted options are displayed

2022-03-02 09:50 UTC, lramarojaona commented
@4hardfire ,
For some reason I cannot save a global event that I'm creating:
```
Warning: Invalid argument supplied for foreach() in Drupal\oec_group_flex\Plugin\GroupVisibility\CustomRestrictedVisibility->validateGroupVisibilityOptions() (line 174 of /app/lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php). 
```

Creating a group works correctly though.

2022-03-03 09:54 UTC, lramarojaona requested changes

2022-03-03 09:55 UTC, lramarojaona commented
@4hardfire , I installed again, and indeed I could create a global event without any issue

2022-03-03 09:55 UTC, lramarojaona requested changes
It works great, I just have one (small) comment.

2022-03-03 14:21 UTC, 4hardfire commented on lib/themes/eic_community/includes/preprocess/groups/group.inc
> + */
Done!

2022-03-03 16:07 UTC, merged