[EICNET-2200] change group teaser title style
EIC-EA/EIC-community-D8 pull request #1315
Opened 2022-03-21 13:27 UTC by Askerx9

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-2200&quickFilter=26822

### What I did

- Now the group title is truncated when it is longer than 2 lines

2022-03-21 15:41 UTC, filipvt1 requested changes

2022-03-21 15:41 UTC, filipvt1 commented on lib/themes/eic_community/sass/compositions/_teaser.scss
> +        min-height: 2.5em;
Don't know if the min-height is needed. If you have 2 groups with short names next to each other you will have extra spacing. Without it the name of the group owner does not align with the next one though (do not know which scenario is more acceptable)

2022-03-21 15:41 UTC, filipvt1 commented on lib/themes/eic_community/sass/compositions/_teaser.scss
> +        white-space: initial;
This isn't needed if you remove the white-space: nowrap line

2022-03-21 15:46 UTC, Askerx9 commented on lib/themes/eic_community/sass/compositions/_teaser.scss
> +        min-height: 2.5em;
Yes, but if you have a block with a long title and one with a short title, you have a blank space at the bottom of the block with the short title.

2022-03-23 08:31 UTC, filipvt1 approved these changes

2022-03-25 07:38 UTC, merged