EICNET-2315: GO can not access Members Pending page
EIC-EA/EIC-community-D8 pull request #1395
Opened 2022-04-08 12:52 UTC by 4hardfire

### Improvements

- Add permission to administer membership request when joining method is set to "tu_group_membership_request";
- Create hook_update to update group permissions for old groups.

### Test

Using QA DB:

- [ ] Run `drush updb`
- [ ] Make sure the following the GO can access the group membership requests page (joining method set to **Request**) -> `/groups/test-private-group/members-pending`
- [ ] Make GO cannot access the group membership requests page for the following group (joining method set to **Open**) -> `/groups/edegem-v2/members-pending`

On a fresh install:

- [ ] As TU, create a new group and set the joining method to "Request"
- [ ] Make sure the user can access the group membership requests page -> `/groups/<group-name>/members-pending`

2022-04-13 09:08 UTC, lramarojaona requested changes

2022-04-13 09:08 UTC, lramarojaona commented on lib/modules/eic_groups/eic_groups.install
> +        $ownerGroupRoleId = EICGroupsHelper::getGroupTypeRole($group_type, 'owner');
Here you could use `EICGroupsHelper::GROUP_TYPE_OWNER_ROLE`

Also believe GA should also be able to manage membership requests

2022-04-13 09:08 UTC, lramarojaona commented on lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
> +use Drupal\eic_groups\EICGroupsHelper;
Ideally we should not have a any dependency of EIC modules in OEC modules.

Since you are only using a static method `getGroupTypeRole`, maybe just replicate this method as a local one?

2022-04-14 12:14 UTC, 4hardfire commented on lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
> +use Drupal\eic_groups\EICGroupsHelper;
Done!

2022-04-14 12:14 UTC, 4hardfire commented on lib/modules/eic_groups/eic_groups.install
> +        $ownerGroupRoleId = EICGroupsHelper::getGroupTypeRole($group_type, 'owner');
Done!

2022-04-14 12:15 UTC, 4hardfire commented
@lramarojaona I updated the code. Can you re-test the PR to make sure it's still working?

2022-04-15 08:08 UTC, lramarojaona approved these changes
Ok  it works!

2022-04-15 12:47 UTC, merged