Feature/eicnet 2468 group invitations migration
EIC-EA/EIC-community-D8 pull request #1566
Opened 2022-05-13 14:14 UTC by lramarojaona

### Improvements

- Added a `hook_mail_alter` to prevent emails to be sent out during migrations

### Tests

- [ ] Run `upgrade_d7_group_pending_invitations`. You should get 1968/1972 migrated items
- [ ] Run `upgrade_d7_group_declined_invitations`. You should get 8/8 migrated items
- [ ] Run `upgrade_d7_group_pending_visitor_invitations`. You should get 875/876 migrated items

2022-05-17 12:27 UTC, 4hardfire reviewed
- Migrate message for upgrade_d7_group_pending_invitations: `upgrade_d7_group_pending_invitations:uid: User not found`
- Migrate message for upgrade_d7_group_pending_visitor_invitations: `upgrade_d7_group_pending_visitor_invitations:gid: Group not found`. This is wrong because the group has been migrated (NID = 10010, Bundle = "event_site")

2022-05-17 12:31 UTC, 4hardfire requested changes

2022-05-17 12:31 UTC, 4hardfire commented on config/sync/migrate_plus.migration.upgrade_d7_group_pending_invitations.yml
> +        - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on config/sync/migrate_plus.migration.upgrade_d7_group_pending_invitations.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on config/sync/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
> +        - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on config/sync/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on config/sync/migrate_plus.migration.upgrade_d7_user_membership.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_declined_invitations.yml
> +        - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_invitations.yml
> +        - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_invitations.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
> +        - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:31 UTC, 4hardfire commented on lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_membership.yml
> +    - upgrade_d7_node_complete_event
This should be `upgrade_d7_node_complete_event_site`

2022-05-17 12:38 UTC, 4hardfire approved these changes

2022-05-17 15:48 UTC, lramarojaona commented on config/sync/migrate_plus.migration.upgrade_d7_group_pending_invitations.yml
> +        - upgrade_d7_node_complete_event
I fixed all the wrong migration names

2022-05-18 08:09 UTC, 4hardfire approved these changes
Seems ok to me!

2022-05-18 08:20 UTC, merged