EICNET-900: Content Recommendation
EIC-EA/EIC-community-D8 pull request #1620
Opened 2022-05-30 09:08 UTC by 4hardfire

### Features

- Create 2 new flags for recommending nodes and groups;
- Create custom module to implement logic for content recommendation.

### Todo

- FE still needs to be implemented.

### Test

Public group:

- [ ] As GM, make sure you can recommend the group via the link "Recommend group" in the group header
- [ ] Click on "Recommend group"
- [ ] Make sure you can select platform users + external user emails
- [ ] Write a message and click confirm
- [ ] Make sure the platform members and external emails received a notification
- [ ] Make sure the same behaviour applies for content inside the group
- [ ] Make sure anonymous users cannot recommend any group or content

Community members group:

- [ ] As GM, make sure you can recommend the group via the link "Recommend group" in the group header
- [ ] Click on "Recommend group"
- [ ] Make sure you can only select platform users (no external emails allowed)
- [ ] Write a message and click confirm
- [ ] Make sure the platform members received a notification
- [ ] Make sure the same behaviour applies for content inside the group

Custom restricted group:

- [ ] As GM, make sure you can recommend the group via the link "Recommend group" in the group header
- [ ] Click on "Recommend group"
- [ ] Make sure you can only select platform users that can access the group (no external emails allowed)
- [ ] Write a message and click confirm
- [ ] Make sure the platform members received a notification
- [ ] Make sure the same behaviour applies for content inside the group

2022-06-14 15:29 UTC, lramarojaona requested changes

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/eic_recommend_content.module
> + * @see https://www.drupal.org/node/2217931
You should get rid of this

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/eic_recommend_content.services.yml
> +  eic_message_subscriptions.flag_event_subscriber:
Shouldn't the module's services always be prefixed with the module name?

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Access/RecommendContentAccessCheck.php
> +        if ($account->isAnonymous()) {
Since the module doesn't provide permissions and access check is done in code, I would definitely put this check higher, as this one doesn't cost anything. Personnally I would put it on line 84.

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          $group_content = reset($group_contents);
Here you are assuming that the group content is always a _content_ membership.
I recommend to use `EICGroupsHelper::getOwnerGroupByEntity()`

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +        'modal_description' => $this->t('Select exisiting members or people outside of the platform you wish to recommend this content to. Those will be presented to you as long as they have the perm
_Select exisiting members or people outside of the platform_

People outside of the platform doesn't apply for community/restriced groups

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          <p>The content you've recommended was successfully sent to the users you've selected. They will receive an email notification informing the of this action.</p>
The content you've recommended was successfully sent to the users you've selected. They will receive an email notification informing the**m** of this action.

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          <p>You can always recommend this content again at a lated stage.</p>"
You can always recommend this content again at a late**r** stage.

2022-06-14 15:29 UTC, lramarojaona commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +        $group_contents = $this->entityTypeManager->getStorage('group_content')
Same remark, you should use `EICGroupsHelper::getOwnerGroupByEntity()`

2022-06-15 08:07 UTC, 4hardfire commented on lib/modules/eic_recommend_content/eic_recommend_content.module
> + * @see https://www.drupal.org/node/2217931
Fixed!

2022-06-15 08:07 UTC, 4hardfire commented on lib/modules/eic_recommend_content/eic_recommend_content.services.yml
> +  eic_message_subscriptions.flag_event_subscriber:
Fixed!

2022-06-15 08:08 UTC, 4hardfire commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          <p>The content you've recommended was successfully sent to the users you've selected. They will receive an email notification informing the of this action.</p>
Fixed!

2022-06-15 08:08 UTC, 4hardfire commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          <p>You can always recommend this content again at a lated stage.</p>"
Fixed!

2022-06-15 08:08 UTC, 4hardfire commented on lib/modules/eic_recommend_content/src/Access/RecommendContentAccessCheck.php
> +        if ($account->isAnonymous()) {
Done!

2022-06-15 08:08 UTC, 4hardfire commented on lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php
> +          $group_content = reset($group_contents);
Done!

2022-06-15 14:48 UTC, merged