EICNET-2539: No validation error message shown when required fields in inactive tabs are empty
EIC-EA/EIC-community-D8 pull request #1742
Opened 2022-06-30 12:27 UTC by 4hardfire

### Improvements

- Remove html5 validation from all forms;
- Show required field label on entity tree widget react component after user submits the form.

### Test

- [ ] As TU (GM), try to add a discussion in a group
- [ ] Leave the Topics and Regions & Countries fields empty
- [ ] Click on save
- [ ] Make sure the page is refreshed and the field group "Topics, countries & tags" is already selected and you see a required label on both Topics and Regions & Countries fields: 
![image](https://user-images.githubusercontent.com/9576940/176676183-c490ea3c-7e10-4d8a-9d2a-50652f311b7d.png)

- [ ] Try to edit an existing discussion
- [ ] Remove all selected terms from the Topics field
- [ ] Click on save
- [ ] Make sure the page is refreshed and the field group "Topics, countries & tags" is already selected + you see a required label in the topics field + there are no selected terms for the topics field

2022-06-30 14:49 UTC, 4hardfire commented
@lramarojaona found this that might fix the issue -> https://www.drupal.org/project/field_group/issues/2969051

2022-06-30 15:16 UTC, lramarojaona commented
@4hardfire I think we should as well collapse paragraph fields that are not required, otherwise it looks like some fields are required even if they are not (both in groups and organisations, maybe check events as well).
This ticket looks like a good candidate to tackle that, wdyt?

2022-07-01 07:52 UTC, 4hardfire commented
> @4hardfire I think we should as well collapse paragraph fields that are not required, otherwise it looks like some fields are required even if they are not (both in groups and organisations, maybe check events as well). This ticket looks like a good candidate to tackle that, wdyt?

Done!

2022-07-05 09:32 UTC, lramarojaona requested changes

2022-07-05 09:32 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Field/EntityTree/index.js
> +    // Uncomment line bellow if we use html5 form validation.
@4hardfire ,
You re-enabled HTML5 validation right?
Do we need this? (Or do we need this comment?)

2022-07-05 09:32 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Field/EntityTree/index.js
> +    // Uncomment line bellow if we use html5 form validation.
@4hardfire ,
You re-enabled HTML5 validation right?
Do we need this? (Or do we need this comment?)

2022-07-05 11:05 UTC, 4hardfire commented on lib/themes/eic_community/react/components/Field/EntityTree/index.js
> +    // Uncomment line bellow if we use html5 form validation.
HTML5 validation is on. I removed the comment.

2022-07-05 11:06 UTC, lramarojaona approved these changes

2022-07-05 11:15 UTC, merged