[EICNET-2610]fix: Fix solr indexing issues due to null group/file
EIC-EA/EIC-community-D8 pull request #1749
Opened 2022-07-03 19:03 UTC by Dromadoros

How to test it:

- [ ] You can just take DB from QA and try reindexing everything, verify that no errors are shown

2022-07-04 09:58 UTC, 4hardfire requested changes

2022-07-04 09:58 UTC, 4hardfire commented on lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
>    }
I believe I did some improvements in here -> https://github.com/EIC-EA/EIC-community-D8/pull/1748/files. Can you have a look?

2022-07-05 07:21 UTC, Dromadoros commented on lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
>    }
I can remove this change but we still need the other

2022-07-07 07:55 UTC, 4hardfire commented on lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
>    }
I resolved the conflicts with develop branch.

2022-07-07 07:55 UTC, 4hardfire approved these changes
This is ok!

2022-07-07 07:56 UTC, merged