EICNET-2670: As a user, I want a limit on group invitation reminders so that I am not spammed
EIC-EA/EIC-community-D8 pull request #1846
Opened 2022-07-27 16:22 UTC by 4hardfire

### Improvements

- Save number of times an invitation has been sent and the date of the last reminder;
- Improve the group invitation reminder cron job in order to skip sending reminders of old invitations;
- limit number of reminders to 3 and send every 3 days.

### Test

For BE dev review:

- [ ] Comment lines 296, 297, 298 of **modules/eic_groups/src/Hooks/CronOperations.php** file
- [ ] Make sure you have old pending invitations in a group
- [ ] Run cron
- [ ] Make sure the users receive a notification about the reminder
- [ ] Do a DB query to change the value in the table **group_content__field_invitation_reminder_count**: column **field_invitation_reminder_count_value** = 3
- [ ] Clear the cache and run cron again
- [ ] Make sure the reminder for the invitations with the field_invitation_reminder_count_value = 3 is not sent
- [ ] Do a DB query to change the value in the table **group_content__field_invitation_reminder_date**: Column **field_invitation_reminder_date_value** = <unix-timestamp-of-3-days-ago>
- [ ] Clear the cache and run cron again
- [ ] Make sure the reminder for the invitations with the field_invitation_reminder_date_value = 3-days-ago is not sent

For QA:

- To test this you should follow the acceptance criteria in the ticket https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2670.

2022-09-07 14:21 UTC, lramarojaona requested changes

2022-09-07 14:21 UTC, lramarojaona commented on config/sync/field.field.group_content.event-group_invitation.field_invitation_reminder_count.yml
> +uuid: a6ecc22c-4cda-45ac-b5d6-97da9112fcd4
Would be way better to create those fields through `hook_entity_bundle_field_info()` so that the site won't break if they add a new Group type (they might add other group types in the future like Challenges and Projects).

2022-09-07 14:21 UTC, lramarojaona commented on lib/modules/eic_groups/src/Hooks/CronOperations.php
> +    $skip_invitation_reminder_time = new DrupalDateTime('today -' . Settings::get('cron_interval_group_skip_invite_reminder_time', 86400 * 30) . ' days');
You should create a Config for that and not a setting.
See: https://drupal.stackexchange.com/questions/227983/how-to-know-when-to-use-config-or-settings-overrides-in-settings-php

Also your calculation is wrong here:
`86400 * 30) . ' days'`
You don't need 86400 cause you are using `days`

2022-09-07 14:21 UTC, lramarojaona commented on lib/modules/eic_groups/src/Hooks/CronOperations.php
> +    $reminder_frequency_time = new DrupalDateTime('today -' . Settings::get('cron_interval_group_invite_reminder_frequency_time', 86400 * 3) . ' days');
You should create a Config for that and not a setting.
See: https://drupal.stackexchange.com/questions/227983/how-to-know-when-to-use-config-or-settings-overrides-in-settings-php

Also your calculation is wrong here:
`86400 * 30) . ' days'`
You don't need 86400 cause you are using `days`

2022-09-09 08:34 UTC, 4hardfire commented on lib/modules/eic_groups/src/Hooks/CronOperations.php
> +    $skip_invitation_reminder_time = new DrupalDateTime('today -' . Settings::get('cron_interval_group_skip_invite_reminder_time', 86400 * 30) . ' days');
Done!

2022-09-09 08:34 UTC, 4hardfire commented on lib/modules/eic_groups/src/Hooks/CronOperations.php
> +    $reminder_frequency_time = new DrupalDateTime('today -' . Settings::get('cron_interval_group_invite_reminder_frequency_time', 86400 * 3) . ' days');
Done!

2022-09-09 10:15 UTC, 4hardfire commented on config/sync/field.field.group_content.event-group_invitation.field_invitation_reminder_count.yml
> +uuid: a6ecc22c-4cda-45ac-b5d6-97da9112fcd4
This is done. When installing group_invitation content in a group, the fields configurations are automatically added.

2022-09-09 12:10 UTC, lramarojaona approved these changes
Ok, it works!

2022-09-09 12:46 UTC, merged