EICNET-2734:
EIC-EA/EIC-community-D8 pull request #1895
Opened 2022-08-11 10:59 UTC by 4hardfire

### Fixes

- Disable job title field for SMED users.

### Test

- [ ] As TU (with SMED ID), try to edit your profile information
- [ ] Make sure the Job title field is readonly
- [ ] As SA/SCM, edit the profile information of the previous TU
- [ ] Make sure you can edit the Job title field
- [ ] As TU (without SMED ID), try to edit your profile information
- [ ] Make sure you can edit the Job title field. This should only happen for users without SMED ID.

2022-08-11 12:38 UTC, lramarojaona requested changes

2022-08-11 12:38 UTC, lramarojaona commented on lib/modules/eic_user/src/Hooks/FormAlter.php
> +    $user = \Drupal::routeMatch()->getParameter('user');
It would be better to get the user from the form directly, and I guess we don't need to test the entity as this is the user form:
```
  /** @var \Drupal\user\UserInterface $type */
  $user = $form_state->getFormObject()->getEntity();
```

2022-08-11 15:52 UTC, 4hardfire commented on lib/modules/eic_user/src/Hooks/FormAlter.php
> +    $user = \Drupal::routeMatch()->getParameter('user');
Done!

2022-08-12 10:07 UTC, lramarojaona requested changes

2022-08-12 10:07 UTC, lramarojaona commented on lib/modules/eic_user/src/Hooks/FormAlter.php
> +    if (
We could put this logic in UserHelper, such as
```
UserHelper::isSmedUser(Account $user): bool{}
```
So we can re-use this, as I believe there will be more stuff like this in the future

2022-08-12 10:26 UTC, 4hardfire commented on lib/modules/eic_user/src/Hooks/FormAlter.php
> +    if (
I agree with you. It's done!

2022-08-12 10:29 UTC, lramarojaona approved these changes

2022-08-12 13:02 UTC, merged