EICNET-2798: Filters on a the topics do not point to correct taxonomy
EIC-EA/EIC-community-D8 pull request #1951
Opened 2022-09-08 15:17 UTC by 4hardfire

### Fixes

- Add cache url.path as cache context in topic statistics block.
- Fix issue where News content type was not shown in Stories overview page.

### Test

- [x] As any user, go to /topics
- [x] Select a topic
- [x] In the topic detail page check the statistics block and click in one of them
- [x] Make sure you get redirected to the overview page with the correct topic as a filter
- [x] Go to a different topic detail page
- [x] Make sure the statistics are different and correct according to the selected topic
- [x] Click in one of the statistics and make sure you get redirected to the overview page with the correct topic as a filter

### Test stories overview

- [x] As any user, go to /stories
- [x] Make sure you can see stories and news

2022-09-09 15:29 UTC, lramarojaona requested changes

2022-09-09 15:29 UTC, lramarojaona commented on lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
> +    return ['news', 'story'];
@4hardfire ,
Whe should not show News in the Stories overview, this is a fix we made few weeks ago, following the client's requirement.

2022-09-13 13:53 UTC, 4hardfire commented on lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
> +    return ['news', 'story'];
Reverted back!

2022-09-13 14:15 UTC, Dromadoros approved these changes

2022-09-13 14:50 UTC, merged