EICNET-2747: As a participant (trusted user) to a SMED Event i should no be able leave an event
EIC-EA/EIC-community-D8 pull request #1987
Opened 2022-09-29 07:18 UTC by 4hardfire

### Improvements

- Alter entity.group.leave route and add custom access check to validate if a group is a SMED group before allowing user to leave group;
- Create hook update to add missing group permission "delete memberships" to GO/GA;
- Add logic to deny access to delete GAs from SMED groups.

### Test

TBD

2022-10-03 10:37 UTC, lramarojaona requested changes

2022-10-03 10:37 UTC, lramarojaona commented on lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
> +      if (
This condition is not ok.
If the user is is a power user, the condition does not apply, then a GO/GA can delete a GA if the user is a power user.

2022-10-03 10:37 UTC, lramarojaona commented on lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
> +      $has_delete_permission = ($current_member->hasPermission('administer members') ||
This is wrong, if I'm a power user not part of the group (outsider), I'm getting this error:
`Error: Call to a member function hasPermission() on bool in eic_group_membership_group_content_access() (line 528 of /app/lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module). `

In fact we should check the permissions of both member roles and outsider roles.

This small module might be very ufseful: https://www.drupal.org/project/group_outsider_in

See: https://www.drupal.org/project/group/issues/2884662

2022-10-03 10:37 UTC, lramarojaona commented on lib/modules/eic_groups/src/EICGroupsHelper.php
> +  public static function isSmedGroup(GroupInterface $group) {
For this we can use `Drupal\eic_webservices\Utility\EicWsHelper::isCreatedThroughSmed()`.

If you think it's more convenient to have it in `EICGroupsHelper`, then just make this method a wrapper method of `Drupal\eic_webservices\Utility\EicWsHelper::isCreatedThroughSmed()`.

2022-10-04 16:12 UTC, 4hardfire commented on lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
> +      if (
I changed the condition but we still assume that SA/SCM users can delete everyone (except the group owner).

2022-10-04 16:13 UTC, 4hardfire commented on lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
> +      $has_delete_permission = ($current_member->hasPermission('administer members') ||
I refactored the code and installed the contrib module. Can you validate @lramarojaona?

2022-10-04 16:13 UTC, 4hardfire commented on lib/modules/eic_groups/src/EICGroupsHelper.php
> +  public static function isSmedGroup(GroupInterface $group) {
Done!

2022-10-12 12:45 UTC, lramarojaona approved these changes
Ok, it works!

2022-10-12 15:42 UTC, merged