Feature/eicnet 2722 flag access check
EIC-EA/EIC-community-D8 pull request #2002
Opened 2022-10-05 08:29 UTC by lramarojaona

### Improvements

- Moved our custom logic for `isPublished()` and `isArchived()` to a new `Drupal\eic_moderation\ModerationHelper` service
- Refactored the code in theme for testing the access to share

### Tests

- [ ] As SA, create a Public group and publish it, make sure you can like and share on social media
- [ ] Create a Document, Discussion, Video, Gallery and Event as Draft (unpublished)
- [ ] Make you sure you cannot like and share on all of them
- [ ] Publish them and make sure you can like and share
- [ ] Unpublish the group
- [ ] Make sure you cannot like and share the Group, Document, Discussion, Video, Gallery and Event

2022-10-12 07:43 UTC, 4hardfire requested changes
Code seems fine but some steps didn't pass:

- `As SA, create a Public group and publish it, make sure you can like and share on social media`
When the group is pending I still see the share link. Also, for some reason the like button is never shown even if the group is published

- `Make you sure you cannot like and share on all of them`
After creating a group content, the share button is always shown (even in draft). The like button is ok.

- `Make sure you cannot like and share the Group, Document, Discussion, Video, Gallery and Event`
The like button is never shown in the group header (even when group is published) and the share button is always shown independently of the group status. For the group content, the like button is ok but the share button is always shown independently of the node moderation state or group moderation state.

2022-10-12 14:50 UTC, 4hardfire requested changes

2022-10-12 14:50 UTC, 4hardfire commented on lib/modules/eic_moderation/src/ModerationHelper.php
> +<?php
I would put this file inside eic_moderation/src/Services

2022-10-12 16:02 UTC, lramarojaona commented on lib/modules/eic_moderation/src/ModerationHelper.php
> +<?php
Well, we already have lots of Helper classes that are the src root

2022-10-12 16:03 UTC, lramarojaona commented
> Code seems fine but some steps didn't pass:
> 
>     * `As SA, create a Public group and publish it, make sure you can like and share on social media`
>       When the group is pending I still see the share link. Also, for some reason the like button is never shown even if the group is published
> 
>     * `Make you sure you cannot like and share on all of them`
>       After creating a group content, the share button is always shown (even in draft). The like button is ok.
> 
>     * `Make sure you cannot like and share the Group, Document, Discussion, Video, Gallery and Event`
>       The like button is never shown in the group header (even when group is published) and the share button is always shown independently of the group status. For the group content, the like button is ok but the share button is always shown independently of the node moderation state or group moderation state.

@4hardfire , there was some code messing up tieh flags, so the like was always removed.

I fixed the otcher checks.

Can you re-test?

2022-10-13 13:04 UTC, 4hardfire requested changes

2022-10-13 13:04 UTC, 4hardfire commented on lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
> -
Is this removal intended? I remember this was previously requested by the client, to have the Recommend flag in the second position.

2022-10-13 13:05 UTC, 4hardfire commented
> > Code seems fine but some steps didn't pass:
> > ```
> > * `As SA, create a Public group and publish it, make sure you can like and share on social media`
> >   When the group is pending I still see the share link. Also, for some reason the like button is never shown even if the group is published
> > 
> > * `Make you sure you cannot like and share on all of them`
> >   After creating a group content, the share button is always shown (even in draft). The like button is ok.
> > 
> > * `Make sure you cannot like and share the Group, Document, Discussion, Video, Gallery and Event`
> >   The like button is never shown in the group header (even when group is published) and the share button is always shown independently of the group status. For the group content, the like button is ok but the share button is always shown independently of the node moderation state or group moderation state.
> > ```
> 
> @4hardfire , there was some code messing up tieh flags, so the like was always removed.
> 
> I fixed the otcher checks.
> 
> Can you re-test?

This is ok!

2022-10-13 13:05 UTC, 4hardfire commented on lib/modules/eic_moderation/src/ModerationHelper.php
> +<?php
ok

2022-10-13 13:40 UTC, merged