EICNET-2758: [Event] No one should be allowed to comment on a draft story
EIC-EA/EIC-community-D8 pull request #2024
Opened 2022-10-12 15:48 UTC by 4hardfire

### Fixes

- Hide comments block and access to block api endpoints when content is in draft or unpublished state.

### Todo

- [x] Move methods from ContentModerationManager to EICModerationHelper after the following PR has been merged #2002

### Test

- [x] As SA/SCM, create a draft News in a global event
- [x] Make sure you cannot post or reply to comments
- [x] Publish the News and make sure you can post or reply to comments now
- [x] Unpublish the News and make sure you cannot post or reply to comments
- [x] Make sure the same behaviour happens with all group content. Whenever the content is in draft, users cannot post or reply to comments.

2022-10-17 15:50 UTC, lramarojaona requested changes
It works, but I have 2 remarks.

2022-10-17 15:50 UTC, lramarojaona commented on lib/modules/eic_groups/src/Controller/DiscussionController.php
> +  private function loadGroupFromNode(int $node_id): bool {
We already have a similar function in `Drupal\eic_groups\EICGroupsHelper::getGroupFromContent()`

2022-10-19 11:54 UTC, 4hardfire commented on lib/modules/eic_groups/src/Controller/DiscussionController.php
> +  private function loadGroupFromNode(int $node_id): bool {
Done!

2022-10-19 11:54 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
> +   * @param EICGroupsHelper $groups_helper
Fixed!

2022-10-24 09:45 UTC, lramarojaona approved these changes
Ok, it works!

2022-10-26 06:46 UTC, merged