EICNET-1921: Activity stream shows undefined link for deleted content
EIC-EA/EIC-community-D8 pull request #2042
Opened 2022-10-20 12:04 UTC by 4hardfire

### Improvements

- Create hook_update to delete activity stream messages with references to non-existing content.

### Test

- [ ] Import DB from PROD
- [ ] Run hook_update
- [ ] Make sure the activity stream messages that point to non-existing content were deleted
- [ ] Try to create a discussion and post it in the activity stream
- [ ] Try to update the discussion and post it in the activity stream
- [ ] Go to the latest activity of the group
- [ ] Make sure you have 2 items
- [ ] Delete the discussion
- [ ] Make sure any message related to the discussion is shown in the activity stream
- [ ] Check the database table `message__field_referenced_node` to see if there is still 2 references to the deleted node
- [ ] Run cron
- [ ] Make sure the rows were removed from the database

2022-10-24 13:02 UTC, lramarojaona requested changes

2022-10-24 13:02 UTC, lramarojaona commented on lib/modules/eic_messages/eic_messages.install
> +    ->setTitle(t('Processing Batch to modify group permissions.'))
Message should be updated here.

2022-10-26 06:53 UTC, 4hardfire commented on lib/modules/eic_messages/eic_messages.install
> +    ->setTitle(t('Processing Batch to modify group permissions.'))
Fixed!

2022-10-27 09:31 UTC, lramarojaona approved these changes
Ok, it works!

2022-10-27 11:48 UTC, merged