EICNET-657: moderated join method on Group
EIC-EA/EIC-community-D8 pull request #226
Opened 2021-05-13 08:14 UTC by jaapjan

**Note: Work is done. But there is some refactoring in https://github.com/EIC-EA/EIC-community-D8/pull/225 which will need to be merged. After that I'll merge develop back into this branch and make sure to solve merge conflicts and move the contents `eic_messages_group_content_insert()` to the correct class.**

**Task 1**
Group creator should be able to create a group with joining method "Request membership" so trusted users will be able to request access.

Solution: build our own custom "Request" joining method plugin and disable the default request joining method.

**Task 2**
Group owner should receive e-mail notification when trusted user request membership.

Solution: react on entity_insert of type group_content and create a message of type `notify_new_membership_request` with the correct field content. 

**How to test:**

Task 1:
- [ ] Create a group with Request joining method as administrator. Make sure it's published.
- [ ] Login as authenticated user.
- [ ] Open the group page and notice the group does not have a "request" button in the local actions menu.
- [ ] Assign the role "trusted user" to the authenticated user.
- [ ] Re-open the group page and notice you can request membership to the group.

Task 2:
- [ ] Request membership to the group.
- [ ] Run the cron.
- [ ] Notice the group owner received a notification e-mail with links to either rejection or accepting.
- [ ] Notice the behaviour of these links is correct and the user is either accepted or rejected. See /group/x/members-pending for the membership request overview.

2021-05-19 13:58 UTC, 4hardfire commented on lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
> +    $groupRoleSync = \Drupal::service('group_role.synchronizer');
Same as PR #225.

2021-05-19 13:59 UTC, 4hardfire requested changes
There is just one remark that is concerning the dependency injection but besides that everything seems fine to me.

2021-05-19 15:20 UTC, jaapjan commented on lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
> +    $groupRoleSync = \Drupal::service('group_role.synchronizer');
Should be done now

2021-05-19 15:21 UTC, jaapjan commented
Solved the merge conflicts and moved the eic_messages_group_content_insert to the correct class. 

Also added dependency injection for the group role synchronizer.

2021-05-20 08:10 UTC, 4hardfire approved these changes
Everything is working fine. Thanks!

2021-05-20 08:26 UTC, merged