Feature/eicnet 541 as a commenter i should be added as contributor to a discussion page
EIC-EA/EIC-community-D8 pull request #231
Opened 2021-05-17 09:59 UTC by fonteijne

2021-05-19 16:08 UTC, jaapjan requested changes
Over all it works. User is added to the contributors when he/she adds a comment or a reply to a comment on a discussion.

Few remarks/todos:

- [ ] Author of the discussion is missing. It needs to be added manually when creating a discussion (According to the description of the story the content creator needs to be there).
- [ ] When you delete your comment and there are no more comments left in the discussion you are still marked as a contributor.

Technicality:

* When you have opened the edit form of the discussion and in the mean time somebody else adds a comment you'll end up with this message "The content has either been modified by another user, or you have already submitted modifications. As a result, your changes cannot be saved.". Not sure how to solve this and if this should even be in the scope.

2021-05-20 08:12 UTC, fonteijne commented on lib/modules/eic_comments/src/Hooks/EntityOperations.php
> +    if ($commentedEntityBundle !== "discussion") {
Done!

2021-05-20 10:02 UTC, jaapjan commented
The other feedback is moved to follow-up stories. So approved 🚀

2021-05-20 10:03 UTC, jaapjan approved these changes

2021-05-20 10:07 UTC, merged