EICNET-777: Implement search suggestions (Did you mean?)
EIC-EA/EIC-community-D8 pull request #248
Opened 2021-05-26 14:03 UTC by didierdemaeyer

Installed the `search_api_spellcheck` module and added the "Did you mean" spellcheck in the header of the global and group search pages.

### Issues

The spellcheck block is displayed on the group search page (/{group}/search-group), but not on the global search page (/search).

2021-05-27 16:16 UTC, 4hardfire reviewed
@didierdemaeyer, I've added the missing header in the twig template used in the global view.

2021-05-27 16:19 UTC, 4hardfire requested changes

2021-05-27 16:19 UTC, 4hardfire commented on composer.json
> -        "drupal/search_api_sorts": "^1.0",
@didierdemaeyer Did you remove the module **search_api_sorts** by mistake? I checked all the configurations and the module seems to be used.
Can you have a look?

2021-05-28 10:28 UTC, didierdemaeyer commented on composer.json
> -        "drupal/search_api_sorts": "^1.0",
Yes, I must've removed that by accident. I've re-added it.

2021-05-31 14:17 UTC, 4hardfire approved these changes
Seems ok to me!

2021-06-02 15:10 UTC, merged