EICNET-811: Overview groups - split up search input and items per page selection
EIC-EA/EIC-community-D8 pull request #254
Opened 2021-05-28 10:18 UTC by 4hardfire

### Description

This PR introduces a solution to split up search input and items per page selection in overview pages. Note that this is only working in Groups overview page (/groups).

- [ ] Place duplicated views exposed form in groups overview (Groups overview context - /admin/structure/context/groups_overview) ;
- [ ] Make sure views exposed forms have unique id attributes when shown multiple times on the page.

### Front-end issues

- [ ] Hide the search input in the second form;
- [ ] Hide the items per page input from the first form;
- [ ] Trigger form submit when changing the items per page.

2021-06-03 16:01 UTC, lramarojaona requested changes

2021-06-03 16:01 UTC, lramarojaona commented on lib/modules/eic_theme_helper/src/Plugin/Block/ViewsFilterItemsPerPageBlock.php
> +      '#title' => $this->t('Showing'),
@4hardfire , is there any way to get the total number of results in this block?
The design shows: "Showing X of 83"

2021-06-03 16:01 UTC, lramarojaona commented on lib/modules/eic_theme_helper/src/Plugin/Block/ViewsFilterItemsPerPageBlock.php
> +    // // Get the view by id and initializes the right display.
Double comments here ;)

2021-06-07 07:13 UTC, 4hardfire commented on lib/modules/eic_theme_helper/src/Plugin/Block/ViewsFilterItemsPerPageBlock.php
> +    // // Get the view by id and initializes the right display.
Done.

2021-06-07 07:16 UTC, 4hardfire commented on lib/modules/eic_theme_helper/src/Plugin/Block/ViewsFilterItemsPerPageBlock.php
> +      '#title' => $this->t('Showing'),
@lramarojaona, In fact I didn't realize we had the total number of results in front of if. If we need to have everything in the same wrapper this has to be done in the header of the view and transform this block in a view header plugin or something like that. Otherwise there is no way of showing it without executing the view twice.

2021-08-06 08:11 UTC, closed without merging