Feature/eicnet 799 author of a discussion is also shown in the list of contributors
EIC-EA/EIC-community-D8 pull request #255
Opened 2021-05-28 15:29 UTC by fonteijne

2021-05-31 14:11 UTC, 4hardfire requested changes

2021-05-31 14:11 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_discussion/eic_content_discussion.module
> +}
Hi @fonteijne,
This works like a charm, however I would suggest implementing the logic using the **hook_entity_presave()**. This way you avoid saving the entity twice.

2021-05-31 14:25 UTC, fonteijne commented on lib/modules/eic_content/modules/eic_content_discussion/eic_content_discussion.module
> +}
Nice! Just a note from our call:
use the `isNew()` to determine whether the entity is created or updated.

2021-05-31 14:30 UTC, fonteijne commented on lib/modules/eic_content/modules/eic_content_discussion/eic_content_discussion.module
> +}
- [ ] Use `hook_entity_presave()`
- [ ] Use `isNew()` to on run on the "insert" operation.

2021-06-02 15:25 UTC, 4hardfire approved these changes
This seems ok now.

2021-06-02 15:27 UTC, merged