EICNET-675: Add view, add context, add block.
EIC-EA/EIC-community-D8 pull request #258
Opened 2021-05-31 10:39 UTC by DutchYoda

2021-05-31 15:12 UTC, 4hardfire requested changes

2021-05-31 15:12 UTC, 4hardfire commented on lib/modules/eic_default_content/content/block_content/4f006e0d-a618-4283-ad23-132b89f60c11.yml
> +    f8df97c3-5505-47a6-8910-3f2282e6abcf: media
This should be removed. For some reason the export didn't export right.

2021-05-31 15:12 UTC, 4hardfire commented on lib/modules/eic_default_content/content/block_content/4f006e0d-a618-4283-ad23-132b89f60c11.yml
> +  uuid: _meta:
This should be removed. For some reason the export didn't export right.

2021-05-31 15:13 UTC, 4hardfire requested changes

2021-05-31 15:13 UTC, 4hardfire commented on config/sync/context.context.members_overview.yml
> +    blocks:
The page banner block is missing from the context.

2021-05-31 15:15 UTC, 4hardfire requested changes

2021-05-31 15:15 UTC, 4hardfire commented on config/sync/context.context.members_overview.yml
> +        uuid: c8c194e9-1d46-441f-9663-777593ba3947
The page banner block is missing from the context.

2021-05-31 15:26 UTC, 4hardfire commented
@DutchYoda, Could you let me know how can I test the members overview? I had to disable the group members view because both had the same path (/members). After that I created a trusted user and this user didn't show in the overview list.
Am I doing something wrong?

2021-06-03 07:32 UTC, DutchYoda commented on config/sync/context.context.members_overview.yml
> +        uuid: c8c194e9-1d46-441f-9663-777593ba3947
I rebuild the context and re-exported the default content.

2021-06-03 07:33 UTC, DutchYoda commented
> @DutchYoda, Could you let me know how can I test the members overview? I had to disable the group members view because both had the same path (/members). After that I created a trusted user and this user didn't show in the overview list.
> Am I doing something wrong?

I changed the path to /all-members. It should work now. There is some front-end work to be done.

2021-06-03 07:38 UTC, 4hardfire approved these changes
It seems ok to me for the backend. Thanks!

2021-06-07 14:43 UTC, lramarojaona requested changes
Facets are missing, we probably need another solution for the banner, and it seems the frontend deosn't work yet (frontend is out-of-scope for this ticket)

2021-06-14 15:40 UTC, didierdemaeyer commented
### Description

- Add filters: Topics of expertise, Topics of interest, Job title, Language, Location
- Add sort: Last active
- Add placeholder text in search input: "Search for a platform member"

### Test

- [ ] Create some users + member profile with the following fields filled: field_location_address, field_vocab_job_title, field_vocab_language, field_vocab_topic_expertise, field_vocab_topic_interest
- [ ] Go to `/people` and test search, filters and sorts on 
- [ ] Only active users are shown in overview
- [ ] Anonymous user can not access page. Trusted users can access page.

### Not implemented

- [ ] Page Banner block default content. -> Todo in EICNET-851
- [ ] Filters should always display all options (greyed out if 0 results)
- [ ] Sorting on "Most active"

2021-06-15 08:09 UTC, didierdemaeyer commented on lib/modules/eic_default_content/content/block_content/4f006e0d-a618-4283-ad23-132b89f60c11.yml
> +_meta:
@lramarojaona Because the page banners will be implemented in another ticket, I guess I should remove this file?

2021-06-15 08:09 UTC, didierdemaeyer commented on lib/themes/eic_community/templates/blocks/block--members-banner.html.twig
> +{#
@lramarojaona Same here. Because the page banners will be implemented in another ticket, I guess I should remove this file?

2021-06-15 08:10 UTC, lramarojaona commented on lib/modules/eic_default_content/content/block_content/4f006e0d-a618-4283-ad23-132b89f60c11.yml
> +_meta:
@didierdemaeyer , yes please remove banner related stuff

2021-06-15 08:12 UTC, didierdemaeyer commented on lib/themes/eic_community/includes/alter/theme_suggestions/page.inc
> +function eic_community_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
@lramarojaona Not sure what this is added for. Should I keep it or remove it?

2021-06-15 08:23 UTC, lramarojaona commented on lib/themes/eic_community/includes/alter/theme_suggestions/page.inc
> +function eic_community_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
@didierdemaeyer , I believe that would be for the users display in the view, you can keep it

2021-06-15 09:19 UTC, lramarojaona approved these changes
Looks good now

2021-06-15 09:31 UTC, merged