[EICNET-847] feat: create group overview search component
EIC-EA/EIC-community-D8 pull request #271
Opened 2021-06-04 15:42 UTC by Dromadoros

2021-07-05 13:37 UTC, lramarojaona requested changes

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +    type_locked: true
What's this for?
Just trying to understand what it does.

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> -        - group
Is there a reason to remove the 4 items above?

- flag_recommend_group_count
- group_content_entity_id
- group_content_gid
- group_content_type

Not sure if the last 3 are still being used, but let's keep them to be sure.
The first one (recommend count) AFAIK is needed.

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +    label: ID
Please prefix all fields with their entity type for consistency.
`[Group] ID` in this case

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +    type: string
I wouldn't change this, please create a new one with String (we already had the case where we needed to have the same field in both modes, string and text)
`[Content] Body - Fulltext => content_field_body_fulltext`

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +    label: 'Thumbnail image » Media » Image » File » URI » Root-relative file URL'
Same here, please prefix all fields with their entity type :)

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> -  'entity:flagging':
I guess this is also related to the recommend count

2021-07-05 13:37 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +  role_filter:
Do we need this?
We might have content that belong to the anonymous user in the future (if a user is being deleted from the platform)

2021-07-05 13:37 UTC, lramarojaona commented on lib/modules/eic_search/eic_search.routing.yml
> +    _access: 'TRUE'
Maybe use the "access content" permission here for more flexibility (in case they want to restrict access to logged in users only, which was still the case on D7 some time ago)

2021-07-05 13:37 UTC, lramarojaona commented on lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
> +  const AVAILABLE_TYPES = ['group', 'story', 'event', 'organisation', 'global'];
Is this used somewhere?

2021-07-05 13:37 UTC, lramarojaona commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +      'ss_group_user_fullname',
We should integrate the labels here, as the current isn't ideal (translating variables and the need to enable locale module just for that)

2021-07-05 13:37 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
> +                            {this.props.translations.search_text}
I think we don't need this, but a placeholder in the input directly.
Also, it would be nice to configure the placeholder text from the block configuration (this will also allow to be translated in the block config if needed in the future)

2021-07-05 13:47 UTC, Dromadoros commented on config/sync/search_api.index.global.yml
> +  role_filter:
This one was needed for users overview which show by default a user 0 without any data but I will figured it out another way to filter this one for users list

2021-07-05 13:48 UTC, Dromadoros commented on lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
> +  const AVAILABLE_TYPES = ['group', 'story', 'event', 'organisation', 'global'];
It was old stuff, will remove that

2021-07-05 13:54 UTC, Dromadoros commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +      'ss_group_user_fullname',
I see what you mean for those fields but there are a lot of translated labels that needs to be editable in the admin and not a good idea to place all labels editable in the block config cause that means that for each block we will need to set again all labels one by one. 

For example the label : "clear all" or other labels. I don't think it's an issue to enable the translation interface, I'm sure in long term it will be good to have this for our complex features

2021-07-05 13:57 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
> +                            {this.props.translations.search_text}
In the design we have a label above but you're right for the placeholder. 

But it's strange to have a placeholder AND a label

2021-07-06 08:19 UTC, Dromadoros commented on config/sync/search_api.index.global.yml
> -        - group
I will re-add it, I just didn't need it for now

2021-07-08 14:54 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
> +                            {this.props.translations.search_text}
Ok, I was based on the wireframe and not the design

2021-07-08 14:56 UTC, lramarojaona requested changes

2021-07-08 14:56 UTC, lramarojaona commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +    ];
It seems the labels for the sort options are not taken into account yet.

2021-07-08 15:02 UTC, Dromadoros commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +    ];
Yes for the admin but on the FE is more complex, I need 2 translations for each sort cause there is ASC and DESC option. Look at my eic_search.module the trick I did

2021-07-08 15:08 UTC, lramarojaona commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +    ];
Ok, then I suggest the following:
```php
t('@sort_option DESC', ['@sort_option' => $sort_option], ['context' => 'eic_search']);
```
So we avoid using variables in `t()` function and we can disable the locale module.

2021-07-20 08:41 UTC, korhankale commented on lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
> +
Seems you have to much line breaks here

2021-07-20 08:41 UTC, korhankale commented on lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
> +    return t('Group', [], ['context' => 'eic_search']);
When possible we try to use StringTranslationTrait, isn't it better if you add it and use $this->t() ? We'll also be more consistent with the rest of the codebase

2021-07-20 08:41 UTC, korhankale commented on lib/modules/eic_search/src/Search/Sources/UserSourceType.php
> +    return t('User', [], ['context' => 'eic_search']);
Same comment for StringTranslationTrait here and everywhere else actually

2021-07-26 09:49 UTC, lramarojaona requested changes

2021-07-26 09:49 UTC, lramarojaona commented on config/sync/locale.settings.yml
> +cache_strings: true
Do we still need locale module to be enbaled?

2021-07-26 09:49 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> -  flag_recommend_group_count:
We should keep this

2021-07-26 13:36 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +  url:
@Dromadoros , can you explain which kind of URL this is?

2021-07-26 13:39 UTC, Dromadoros commented on config/sync/search_api.index.global.yml
> +  url:
relative url of the entity for eg : 

![image](https://user-images.githubusercontent.com/11585507/126998420-bab3cf5c-455e-488d-be74-39f9970c4e0b.png)

2021-07-26 13:48 UTC, lramarojaona commented on config/sync/search_api.index.global.yml
> +  url:
Ok, just renamed the label for clarity

2021-07-26 13:48 UTC, lramarojaona approved these changes

2021-07-28 14:37 UTC, merged