EICNET-829: Book page sidebar navigation and add book page links (current level / child)
EIC-EA/EIC-community-D8 pull request #282
Opened 2021-06-08 18:04 UTC by didierdemaeyer

* Add book navigation in sidebar for books that do not belong to a group
* Add links to add book page on current level or child page
* Fix circular redirect issue for book pages outside groups (BookPageRedirectSubscriber)
* Hide author and publish date information from wiki pages

### Test

* Create a new book page not linked to a group - /node/add/book
* SA/SCM can see and use add book page links ("Add a new book page" on top level book page) ("Add a new page on the current level" and "Add a new page below this page" on other book pages)
* All site users can see the book navigation in the sidebar for all book pages
* Book and wiki pages that belong to a group are not affected by these changes

2021-06-09 14:19 UTC, Dromadoros commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if (isset($entity->book) && $entity->book['pid'] === '0') {
the pid really returns a string and not an integer ?

2021-06-09 14:21 UTC, Dromadoros commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
I'm not sure but is this not handle by default with group module ? I'm surprised that a node linked to a group can be by default accessible by everyone

2021-06-09 14:30 UTC, Dromadoros commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          unset($build['book_navigation']);
Can we avoid this ? I find it strange to remove the navigation via this preprocess and not config

2021-06-10 08:36 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
Hi @Dromadoros, I've created this method in EICGroupsHelper service so that we could retrieve a group from any given entity. The method itself internally uses the **GroupContent::loadByEntity** to get the group content of a node and then the respective group. In any case I did this to avoid duplicated code.

2021-06-10 08:38 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
But indeed... in this case we could simply check:
`if (GroupContent::loadByEntity($entity))`

2021-06-10 08:47 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          unset($build['book_navigation']);
@Dromadoros, The book_navigation is not something you can control via configuration unfortunatelly. The book module actually adds it to the renderable array:
```php
/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function book_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'full') {
    if (!empty($node->book['bid']) && empty($node->in_preview)) {
      $book_node = Node::load($node->book['bid']);
      if (!$book_node->access()) {
        return;
      }
      $build['book_navigation'] = [
        '#theme' => 'book_navigation',
        '#book_link' => $node->book,
        '#weight' => 100,
        // The book navigation is a listing of Node entities, so associate its
        // list cache tag for correct invalidation.
        '#cache' => [
          'tags' => $node->getEntityType()->getListCacheTags(),
        ],
      ];
    }
  }
}
```

2021-06-10 08:50 UTC, 4hardfire requested changes

2021-06-10 08:50 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
@didierdemaeyer can you check if it is possible to use the condition as follow? -> `if (GroupContent::loadByEntity($entity))`

2021-06-10 09:34 UTC, didierdemaeyer commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if (isset($entity->book) && $entity->book['pid'] === '0') {
@Dromadoros Yes it does. I thought it was weird too

2021-06-10 11:56 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
Changes not needed after all. All good!

2021-06-10 12:39 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if (isset($entity->book) && $entity->book['pid'] === '0') {
@Dromadoros I replaced with an empty function. It works fine.

2021-06-10 12:39 UTC, 4hardfire commented on lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
> +          if ($this->eicContentHelper->getGroupContentByEntity($entity)) {
Changes not needed after all. All good!

2021-06-10 12:40 UTC, 4hardfire approved these changes
It looks fine to me now.

2021-06-14 10:20 UTC, merged