EICNET-870: Implement solution for private / public stories & news articles
EIC-EA/EIC-community-D8 pull request #302
Opened 2021-06-16 14:28 UTC by 4hardfire

### Description

- Created new custom module eic_private_content that exposes a new property "private" on Nodes;
- Enabled private content for CTypes News and Story.

### Todo

- Create custom view access check to allow/restrict access based on private field.

### Tests

- [ ] Enable permission to access admin content overview page for Trusted users;
- [ ] Disable view private content permission for Trusted users;
- [ ] As a content admin, create a new story and mark it as private;
- [ ] As a trusted user navigate to admin content overview page and check if the node is **not** shown in the results;
- [ ] As a content admin, uncheck the private field so the node is now public
- [ ] As a trusted user navigate to admin content overview page and check if the node is shown in the results;
- [ ] Enable permission to view private content for Trusted users;
- [ ] As a content admin, umark the story as private again;
- [ ] As a trusted user navigate to admin content overview page and check if the node is shown in the results;

Homepage:

- [ ] As a content admin, add some private and public stories/news to the homepage latest news and stories block;
- [ ] As anonymous, check if I can only see public news/stories

2021-06-16 16:49 UTC, didierdemaeyer requested changes
Looks good, but there's still one todo in the code.

2021-06-16 16:49 UTC, didierdemaeyer commented on lib/modules/eic_private_content/eic_private_content.module
> +    // @todo Mark all nodes as non private.
@4hardfire Should this still be done in this PR?

2021-06-17 07:24 UTC, 4hardfire commented on lib/modules/eic_private_content/eic_private_content.module
> +    // @todo Mark all nodes as non private.
@didierdemaeyer In my opinion this should be done with cron in a follow-up ticket. Do you agree?

2021-06-17 08:04 UTC, didierdemaeyer commented on lib/modules/eic_private_content/eic_private_content.module
> +    // @todo Mark all nodes as non private.
@4hardfire Yes, that's ok.

2021-06-17 08:46 UTC, didierdemaeyer approved these changes

2021-06-17 08:51 UTC, merged