Feature/EICNET-1017: Admin list improvements
EIC-EA/EIC-community-D8 pull request #327
Opened 2021-06-24 14:56 UTC by korhankale

2021-06-25 11:11 UTC, 4hardfire commented on lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
> +        'class' => [RESPONSIVE_PRIORITY_MEDIUM],
@korhankale where is this **RESPONSIVE_PRIORITY_MEDIUM** come from?

2021-06-25 11:12 UTC, 4hardfire commented on lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
> +        'class' => [RESPONSIVE_PRIORITY_MEDIUM],
My IDE is complaining about it.

2021-06-25 11:15 UTC, korhankale commented on lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
> +        'class' => [RESPONSIVE_PRIORITY_MEDIUM],
Hmm it shouldn't, this is one of the constants drupal define within the global namespace. What IDE are you using?

2021-06-25 11:17 UTC, 4hardfire commented on lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
> +        'class' => [RESPONSIVE_PRIORITY_MEDIUM],
I'm using VS code with WSL. This is fine... I just wanted to make sure this was not an issue :).

2021-06-25 11:18 UTC, 4hardfire commented
@korhankale Are we taking into account pagination in the list of requests?

2021-06-25 11:20 UTC, korhankale commented
> @korhankale Are we taking into account pagination in the list of requests?

Currently we don't, let's not approve this PR. I'll add it this afternoon

2021-06-25 11:23 UTC, 4hardfire requested changes
- [ ] Add missing pager in the list

2021-06-28 08:30 UTC, 4hardfire approved these changes
Seems ok to me.

2021-06-28 08:31 UTC, merged