Feature/EICNET-886: As a SA/SCM I can accept the archival request
EIC-EA/EIC-community-D8 pull request #335
Opened 2021-06-28 12:23 UTC by korhankale

Allows a SA/SCM to accept archival requests

### To Test

- [ ] Make an archival request
- [ ] Go to /admin/community/request/archive and accept the request
- [ ] The content entity should pass to the "archived" state if content moderation is enabled otherwises status = FALSE
- [ ] A message confirming the archival should be sent

2021-06-28 15:23 UTC, 4hardfire requested changes
I am having a PHP error when trying to access the group homepage:
`Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'request-delete' found for the 'group' entity type in Drupal\Core\Entity\EntityBase->toUrl() (line 196 of /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php).`

2021-06-28 15:24 UTC, korhankale commented
> I am having a PHP error when trying to access the group homepage:
> `Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'request-delete' found for the 'group' entity type in Drupal\Core\Entity\EntityBase->toUrl() (line 196 of /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php).`

Indeed, it is fixed by this PR: https://github.com/EIC-EA/EIC-community-D8/pull/332

2021-06-28 15:26 UTC, 4hardfire commented
> > I am having a PHP error when trying to access the group homepage:
> > `Drupal\Core\Entity\Exception\UndefinedLinkTemplateException: No link template 'request-delete' found for the 'group' entity type in Drupal\Core\Entity\EntityBase->toUrl() (line 196 of /var/www/html/web/core/lib/Drupal/Core/Entity/EntityBase.php).`
> 
> Indeed, it is fixed by this PR: #332

Ok lets review this after the other one gets merged.

2021-07-01 07:49 UTC, Dromadoros approved these changes

2021-07-01 07:51 UTC, merged