EICNET-986: Closer to group header redesign
EIC-EA/EIC-community-D8 pull request #340
Opened 2021-06-30 10:23 UTC by xwero

Changes:

- The recommend group flag is working now
- The login button is visible when anonymus (EICNET-1039, EICNET-1047)
- Moved link manipulation to the `EICGroupHeaderBlock` class to make the `eic_community_preprocess_eic_group_header_block` cleaner

Problems:

- The group follow flag is displayed with the lib/themes/eic_community/patterns/components/flag.html.twig template file which is meant to display a country flag. That flag does not render with the `eic_flag_count` theme like the recommend group flag. 
- When a user with a site admin role is not part of a group both 'join group' and 'request membership group' buttons are shown. This could be confusing. 
- There are still open tickets that block some of the scenarios in the subtickets of EICNET-986

2021-06-30 15:34 UTC, 4hardfire requested changes

2021-06-30 15:34 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +      if (strpos($key, 'create') !== false) {
@xwero how many times is this IF condition TRUE? If  it's something that happens once I guess we can do a `break;` at the end of the IF. Also, do you think it would be nice if we add a comment in the beginning of the foreach just to understand what's happening?

2021-06-30 15:34 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +
Can we delete this line?

2021-06-30 15:36 UTC, 4hardfire requested changes

2021-06-30 15:36 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +      $operation_links['anonymus_user_link'] = $login_link;
Typo in `anonymus_user_link`. It should be `anonymous_user_link`.

2021-06-30 15:54 UTC, 4hardfire commented
> Problems:
> 
> * The group follow flag is displayed with the lib/themes/eic_community/patterns/components/flag.html.twig template file which is meant to display a country flag. That flag does not render with the `eic_flag_count` theme like the recommend group flag.
> * When a user with a site admin role is not part of a group both 'join group' and 'request membership group' buttons are shown. This could be confusing.
> * There are still open tickets that block some of the scenarios in the subtickets of EICNET-986

- The flag group follow needs to be changed in the backend. We should be using the option **EIC Count link** and link type;
- I guess we will create a new role for site admins because right now we are assuming the Drupal administrator role and that role can bypass everything. This is the problem;

2021-07-01 07:08 UTC, xwero commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +      if (strpos($key, 'create') !== false) {
All the create links that come from the `$this->eicGroupsHelper->getGroupOperationLinks($group, ['node'], $cacheable_metadata)` are matched, so at the moment it wil happen three times.

Before the rewrite I had to hope that the links in the `operations_links` array where the create links. Now we are sure they are and we can do al lot more link manipulation because the link handling in the preprocess function is now generic.

I added a comment in my last update.

2021-07-01 07:10 UTC, xwero commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +
The unset function can not be removed, that stops the link for appearing a button and as a link in the grey section below the buttons.

2021-07-01 07:11 UTC, xwero commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +      $operation_links['anonymus_user_link'] = $login_link;
Fixed.

2021-07-01 11:22 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +
I mean the empty line :)

2021-07-01 12:07 UTC, 4hardfire approved these changes
It seems fine to me!

2021-07-01 12:47 UTC, merged