Feature/EICNET-838: Implement request accepted logs
EIC-EA/EIC-community-D8 pull request #360
Opened 2021-07-07 15:01 UTC by korhankale

### To Test
- [ ] Accept an archival/delete request
- [ ] A new log type message should be created 
- [ ] The rendered content of this message should be stored within the field_rendered_content_field
- [ ] Mails sent when the request is accepted should have the content of this field using the raw-value:[FIELD_NAME] token

2021-07-12 14:02 UTC, lramarojaona commented
Looks good, maybe just creating 2 seperates log message for accepted deletion/archival requests (we can ask Kris).
Also we'll need to align with the codings standards, as we're not using the same.

2021-07-12 14:20 UTC, korhankale commented on config/sync/message.template.log_request_accepted.yml
> +    value: "<p>Request&nbsp;[message:field_referenced_flag:entity:flag-type] accepted</p>\r\n\r\n<ul>\r\n\t<li>Deleted entity:&nbsp;[message:field_referenced_flag:entity:target_entity:title]</li>\r\n
My opinion would be that we should not handle log templates as those for messages and even try to have one message template for every log and just store texts (also a level/channel maybe). In this case I went for a single one for every request type to avoid increasing the number of message templates

2021-07-12 14:36 UTC, lramarojaona commented on lib/modules/eic_flags/src/Hooks/FlagTokens.php
> +  public function __construct(
Not especially here, but we have there are stronger requirements, I guess from the intial Docker environment (the one provided by Digit)

2021-07-12 14:43 UTC, lramarojaona commented on config/sync/message.template.log_request_accepted.yml
> +    value: "<p>Request&nbsp;[message:field_referenced_flag:entity:flag-type] accepted</p>\r\n\r\n<ul>\r\n\t<li>Deleted entity:&nbsp;[message:field_referenced_flag:entity:target_entity:title]</li>\r\n
Mmmm, yes, that would be nice, but then how do you handle to filter on the log type and have a different message structure per log?

2021-07-12 14:54 UTC, korhankale commented on config/sync/message.template.log_request_accepted.yml
> +    value: "<p>Request&nbsp;[message:field_referenced_flag:entity:flag-type] accepted</p>\r\n\r\n<ul>\r\n\t<li>Deleted entity:&nbsp;[message:field_referenced_flag:entity:target_entity:title]</li>\r\n
I'd say we can have a message template "log" with:
- field channel -> would be the "type"
- (if needed) field level (info and warning maybe?)
- field content/text/log -> pure static text which won't change at all

2021-07-12 15:49 UTC, lramarojaona requested changes

2021-07-12 15:49 UTC, lramarojaona commented on config/sync/language/en/message.template.log_request_accepted.yml
> +    value: "<p>Request&nbsp;[message:field_referenced_flag:entity:flag-type] accepted</p>\r\n\r\n<ul>\r\n\t<li>Entity:&nbsp;[message:field_referenced_flag:entity:target_entity:title]</li>\r\n\t<li>Ty
Can we have the user full name here instead of username?

2021-07-15 08:34 UTC, korhankale commented
Merging this, let's continue the discussion about logs and once we are ok with the way to go, a new implementation might follow up with another PR

2021-07-15 08:34 UTC, merged