EICNET-1051: As a GO I shouldn't be able to add content when my group is in pending state
EIC-EA/EIC-community-D8 pull request #361
Opened 2021-07-07 16:03 UTC by 4hardfire

### Improvements

- Override access_check.group_content.create_entity service class with a custom class GroupContentCreateEntityAccessCheck in order to have extra access conditions and prevent GO from creating content while the group is in pending state;
- Add missing conditions to check group operation links access before adding them to the group header.

### Tests

- [ ] As a trusted user, create a new group;
- [ ] From the group overview page, check if the **Post content** dropdown is not available;
- [ ] Try to manually access the group content creation form through the URL and check if you get an access denied;
- [ ] As a SA/SCM, approve the group (change to draft or published);
- [ ] As a GO, you should now be able to create group content and the "Post content" dropdown should now be available in the group header;

### Todo

- Change the way we add/remove permissions to delete a group as a GO when group has been approved. Right now, we add/remove permission to delete based on the group moderation state but we should be doing an access check on top of the default permissions.

2021-07-12 15:05 UTC, lramarojaona requested changes

2021-07-12 15:05 UTC, lramarojaona commented on lib/modules/eic_groups/eic_groups.module
> +        $access = AccessResult::forbiddenIf(!in_array('administrator', $account->getRoles(TRUE)) && !in_array('content_administrator', $account->getRoles(TRUE)))
Don't know if we have a permission that applies here to do the check, but we should at least use the role constants rather than hard-code them: https://github.com/EIC-EA/EIC-community-D8/blob/develop/lib/modules/eic_user/src/UserHelper.php

2021-07-12 15:05 UTC, lramarojaona commented on lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
> +          $access = AccessResult::forbiddenIf(!in_array('administrator', $account->getRoles(TRUE)) && !in_array('content_administrator', $account->getRoles(TRUE)))
Same here we should use role constants: https://github.com/EIC-EA/EIC-community-D8/blob/develop/lib/modules/eic_user/src/UserHelper.php

2021-07-12 15:12 UTC, lramarojaona commented
Also, it seems I can delete the group as trusted user/GO while it's in pending state, but I guess that's the correct behavior?
It is however wrong if we need to comply to your statement: _"As a Trusted user and GO, make sure you can't delete your group when it's in pending state."_

2021-07-13 09:28 UTC, 4hardfire commented on lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
> +          $access = AccessResult::forbiddenIf(!in_array('administrator', $account->getRoles(TRUE)) && !in_array('content_administrator', $account->getRoles(TRUE)))
Done!

2021-07-13 09:28 UTC, 4hardfire commented on lib/modules/eic_groups/eic_groups.module
> +        $access = AccessResult::forbiddenIf(!in_array('administrator', $account->getRoles(TRUE)) && !in_array('content_administrator', $account->getRoles(TRUE)))
Done!

2021-07-13 09:32 UTC, 4hardfire commented
> Also, it seems I can delete the group as trusted user/GO while it's in pending state, but I guess that's the correct behavior?
That is correct.

> It is however wrong if we need to comply to your statement: _"As a Trusted user and GO, make sure you can't delete your group when it's in pending state."_
The statement was wrong. The right one is: _As a Trusted user and GO, make sure you can't delete your group when it's in draft or published state._. I updated the PR description accordingly.

2021-07-13 14:25 UTC, lramarojaona approved these changes
Looks good now!

2021-07-13 14:33 UTC, merged