EICNET-1055: No need for flags in group header when group is in draft or pending state
EIC-EA/EIC-community-D8 pull request #369
Opened 2021-07-09 13:36 UTC by 4hardfire

### Improvements

- Decorate FlagAccessCheck and UnFlagAccessCheck services in order to provide extra access check logic for group flags;
- Improve EICGroupHeaderBlock class in order to show/hide group flags depending on the access (the acces check was not being triggered);
- Decorate RequestAccessCheck service in order to provide extra access check logic for group flags "request delete" and "request archival".

### Tests

- [ ] Create a new group and set the state to pending;
- [ ] Go to the group overview page and check if the group flags are hidden;
- [ ] Check if you get an access denied when trying to flag the group via URL;
- [ ] Change the group state from pending to draft and check if the access to flags is still denied;
- [ ] Change the group state to published and check if you are now able to flag the group via the group header.

2021-07-12 16:03 UTC, lramarojaona requested changes

2021-07-12 16:03 UTC, lramarojaona commented on lib/modules/eic_groups/src/Access/FlagRequestAccessCheck.php
> +    if ($access->isAllowed()) {
Same here:
```php
if (!$access->isAllowed()) {
  return $access;  
}

// My code...
```

2021-07-12 16:03 UTC, lramarojaona commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +    if (isset($group->flags)) {
Again :)
```php
if (empty($group->flags)) {
  return $group_flags;
}

// Code here.
```

2021-07-13 09:50 UTC, 4hardfire commented on lib/modules/eic_groups/eic_groups.module
> +function eic_groups_flagging_access(EntityInterface $entity, $operation, AccountInterface $account) {
There is no need to create a class for this hook because we don't need to make use of any service. This will make the code run faster because there is no need to construct a new class everytime the hook_access is triggered.
Usually I create a class when I need to make use of a service instead of using \Drupal::service().

2021-07-13 09:50 UTC, 4hardfire commented on lib/modules/eic_groups/src/Access/FlagAccessCheck.php
> +    if ($access->isAllowed()) {
Done!

2021-07-13 09:51 UTC, 4hardfire commented on lib/modules/eic_groups/src/Access/FlagRequestAccessCheck.php
> +    if ($access->isAllowed()) {
Done!

2021-07-13 09:53 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
> +    if (isset($group->flags)) {
Done!

2021-07-13 13:20 UTC, lramarojaona commented on lib/modules/eic_groups/eic_groups.module
> +function eic_groups_flagging_access(EntityInterface $entity, $operation, AccountInterface $account) {
Ok understood

2021-07-13 13:22 UTC, merged