[EICNET-843]feature: Create search input next to group menu
EIC-EA/EIC-community-D8 pull request #385
Opened 2021-07-14 13:37 UTC by Dromadoros

New block/form injected directly next to the group_menu via preprocess. The submit will redirect the user to a route with a query parameter

2021-07-15 16:36 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/SearchMenuGroupBlock.php
> +    $form = \Drupal::formBuilder()->getForm(SearchMenuGroupForm::class);
Can you use dependency injection here instead of calling `\Drupal::formBuilder()`? Usually grumphp should throw an error when you try to use drupal services within a class without using proper dependency injection.
In order to avoid spending time searching about how to implement dependency injection in plugins, I already did that for you :):

- Your class should implement the `Drupal\Core\Plugin\ContainerFactoryPluginInterface`;
- Implement the following create method:
```php
/**
 * {@inheritdoc}
 */
public static function create(
  ContainerInterface $container,
  array $configuration,
  $plugin_id,
  $plugin_definition
) {
  return new static(
    $configuration,
    $plugin_id,
    $plugin_definition,
    $container->get('form_builder')
  );
}
```

- Override the constructor:

```php
public function __construct(
  array $configuration,
  $plugin_id,
  $plugin_definition,
  FormBuilderInterface $form_builder,
) {
  parent::__construct($configuration, $plugin_id, $plugin_definition);
  $this->formBuilder = $form_builder;
}
```

2021-07-15 16:37 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/SearchMenuGroupBlock.php
> + * Provides an SearchMenuGroupBlock block.
I know it sucks but can you replace "an" by "a"? Thanks ;)

2021-07-15 16:42 UTC, 4hardfire commented on lib/modules/eic_groups/src/Form/SearchMenuGroupForm.php
> + * Class SearchMenuGroupForm
Usually GrumPHP will throw an error because it expects a better description for your class other thatn "Class ClassName". Could we have something like: "Provides a class for the group search form."?

2021-07-15 16:50 UTC, 4hardfire requested changes
- Check previous comments;
- There is an issue where the icon next to the search input text is not shown.

2021-07-16 09:12 UTC, Dromadoros commented on lib/modules/eic_groups/src/Form/SearchMenuGroupForm.php
> + * Class SearchMenuGroupForm
Of course my dear deer

2021-07-16 09:23 UTC, Dromadoros commented on lib/modules/eic_groups/src/Plugin/Block/SearchMenuGroupBlock.php
> +    $form = \Drupal::formBuilder()->getForm(SearchMenuGroupForm::class);
Haha thanks for doing my job 🍸 🥥

2021-07-16 09:32 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/SearchMenuGroupBlock.php
> +   * @param \Drupal\Core\Form\FormBuilderInterface $form_builder
Some parameters descriptions are missing:

```php
   * @param array $configuration
   *   The plugin configuration, i.e. an array with configuration values keyed
   *   by configuration option name. The special key 'context' may be used to
   *   initialize the defined contexts by setting it to an array of context
   *   values keyed by context names.
   * @param string $plugin_id
   *   The plugin_id for the plugin instance.
   * @param mixed $plugin_definition
   *   The plugin implementation definition.
   * @param \Drupal\Core\Form\FormBuilderInterface $form_builder
   *   The Form builder service.
```

2021-07-16 09:34 UTC, 4hardfire commented on lib/modules/eic_groups/src/Plugin/Block/SearchMenuGroupBlock.php
> +  /** @var \Drupal\Core\Form\FormBuilderInterface $formBuilder */
Replace with:

```php
  /**
   * The form builder service.
   *
   * @var \Drupal\Core\Form\FormBuilderInterface
   */
```

2021-07-16 09:38 UTC, 4hardfire approved these changes
Seems good to me! Just inform Julie that the icon next to the text input needs to be fixed in a follow-up ticket.

2021-07-16 11:36 UTC, merged