Feature/eicnet 1120
EIC-EA/EIC-community-D8 pull request #394
Opened 2021-07-16 10:06 UTC by speeters1

2021-07-16 10:43 UTC, xwero requested changes

2021-07-16 10:43 UTC, xwero commented on lib/themes/eic_community/patterns/compositions/featured-content-grid.html.twig
> +          {% for key, item in items %}
Is the key variable used? If not, i would not change the loop.

2021-07-19 10:46 UTC, speeters1 commented on lib/themes/eic_community/patterns/compositions/featured-content-grid.html.twig
> +          {% for key, item in items %}
It's used on line 67 to check if the item is the first one of the for loop. Normally I would use the loop variable but that doesn't seem to work

2021-07-19 13:39 UTC, xwero approved these changes

2021-07-22 09:06 UTC, merged