EICNET-1113: Implement the missing statistics to the group header
EIC-EA/EIC-community-D8 pull request #396
Opened 2021-07-16 11:47 UTC by 4hardfire

### Features

- Create module eic_group_statistics;
- Create new custom schema for saving group statistics;
- Implement statistics counter for group members;
- Delete group statistics when group is deleted.

### Tests (TBD)

2021-07-22 06:07 UTC, xwero approved these changes
Adding members and comments increments the statistics.
And the statistics are shown according to the design.

2021-07-26 10:49 UTC, lramarojaona requested changes

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
> +  $group_statistics_storage->setMultipleGroupStatistics($groups_statistics);
Should we put this logic as a separate function for later use (somewhere in the module)?

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  switch ($entity->bundle()) {
Should we put the switch directly in the EntityOperations->groupContentInsert() method instead of here?
For consistency with the other ones.

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  \Drupal::service('eic_group_statistics.search_api.reindex')->reindexItem($group_content->getGroup());
Why don't you use the EntityOperations class here?

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
> +    return $group_statistics;
Maybe `return $this->groupStatisticsStorage->load($group);` to avoid creating a useless variable?

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
Maybe we could get this list dynamically, fields in nodes (only?) that reference media items.

https://drupal.stackexchange.com/questions/222731/how-to-get-all-field-name-of-field-type

2021-07-26 10:49 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
> +      GroupStatisticsStorageInterface::STAT_TYPE_EVENTS => $this->t('Events'),
Maybe we could have the labels in the same class as the constants, so we can re-use them elsewhere.
Also, probably not in the interface class.
I was looking for an example but cannot find out right now.

2021-07-26 11:07 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  switch ($entity->bundle()) {
I wouldn't recommend that because you don't need to instantiate a class with services if the group content bundle is not those listed in that switch. At least this way we improve performance.

2021-07-26 11:09 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
> +      GroupStatisticsStorageInterface::STAT_TYPE_EVENTS => $this->t('Events'),
Usually I define constants in the interfaces. Not sure if this is a standard but I remember doing this in other projects. Maybe I should look into drupal core classes to see how they do it.

2021-07-26 11:21 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
> +  $group_statistics_storage->setMultipleGroupStatistics($groups_statistics);
Done.

2021-07-26 11:25 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  \Drupal::service('eic_group_statistics.search_api.reindex')->reindexItem($group_content->getGroup());
I think this hook is so simple that I thought there was no need to instantiate EntityOperations. Also because we will then instantiate 2 more services which we won't need and we might have a lot of comments being added and removed all the time. I don't know but maybe we get a little performance improvements. Services and classes are useful but sometimes it slows down things.

2021-07-26 11:26 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
> +    return $group_statistics;
Done.

2021-07-26 13:38 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
There is a field_related_media in Wiki pages and it can be an image or a remote video. I am not sure if this should be taken into account for the statistics. That's why I hardcoded the fields we needed. Do you have any suggestion? I guess we need to hardcode something at least.

2021-07-26 13:52 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  switch ($entity->bundle()) {
Mmm, yeah ok, we're doing the same in other hooks, let's see

2021-07-26 13:56 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
> +      GroupStatisticsStorageInterface::STAT_TYPE_EVENTS => $this->t('Events'),
Found the example I was looking for: https://github.com/EIC-EA/EIC-community-D8/blob/develop/lib/modules/eic_messages/src/MessageTemplateTypes.php
There are other examples accross our codebase, just search for `const ` (with a trailing space)

2021-07-26 13:57 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
> +  \Drupal::service('eic_group_statistics.search_api.reindex')->reindexItem($group_content->getGroup());
Ok

2021-07-26 13:59 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
Ok, if we need to hardcode some of them, then maybe use a config? (no ui)

2021-07-26 14:02 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
In the future we could improve this and probably create a configuration form to select which bundles and fields to use for the file statistics.

2021-07-26 14:08 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
Ok, maybe add a todo then, so we can find future potential improvements easily

2021-07-26 14:44 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
> +      GroupStatisticsStorageInterface::STAT_TYPE_EVENTS => $this->t('Events'),
Done.

2021-07-26 15:18 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
> +        ];
Done.

2021-07-26 15:20 UTC, lramarojaona approved these changes
Looks good!

2021-07-26 15:21 UTC, merged