EICNET-1128: Show drupal and group status messages in storybook styling.
EIC-EA/EIC-community-D8 pull request #407
Opened 2021-07-22 09:31 UTC by xwero

Tests:

- [] Create a group in the pending state
- [] *the group created message and the pending message should be visible and styled*
- [] Change the state of the group to draft
- [] *An updated group, an approved and a get the conversation started message should be visible and styled*
- [] Change the state of the group to published
- [] *An updated group, a published and a get the conversation started message should be visible and styled*

2021-07-29 13:13 UTC, didierdemaeyer commented
Tested the PR. 

The group status messages and the get the conversation started are OK, but I don't see the drupal messages (created group, updated group) at all.

2021-07-29 14:32 UTC, didierdemaeyer requested changes
Tested the PR.

The group status messages and the get the conversation started are OK, but I don't see the drupal messages (created group, updated group) at all.

2021-07-30 08:50 UTC, Dromadoros approved these changes

2021-07-30 11:04 UTC, didierdemaeyer approved these changes

2021-07-30 12:03 UTC, merged