[EICNET-580]feature: Add facets languages and roles + sorts fort last active user
EIC-EA/EIC-community-D8 pull request #454
Opened 2021-08-02 21:52 UTC by Dromadoros

How to test :

- [ ] Go to /people
- [ ] Check if there are language  + role filter and last active sort option

2021-08-03 09:31 UTC, 4hardfire commented on config/sync/search_api.index.global.yml
> -      - recommend_group
@Dromadoros Is this ok or was it a mistake?

2021-08-03 09:32 UTC, 4hardfire reviewed
Check my last comment before I approve it.

2021-08-03 10:56 UTC, 4hardfire requested changes
- [ ] Revert config

2021-08-03 13:32 UTC, Dromadoros commented on config/sync/search_api.index.global.yml
> -      - recommend_group
Done

2021-08-04 07:42 UTC, 4hardfire approved these changes
Seems ok to me!

2021-08-04 08:44 UTC, merged