EICNET-1336: File download counter refactoring
EIC-EA/EIC-community-D8 pull request #548
Opened 2021-08-27 13:54 UTC by 4hardfire

### Improvements

- Download and install module "media_entity_download";
- Create custom access check to control access to the media file download route;
- Move code from hook eic_media_statistics_file_download to the MediaFileDownloadController.

### Tests

- [ ] Create a document with 2 medias (make sure you are on private download method, this is provided in the config)
- [ ] Download the media 1
- [ ] Download the media 2
- [ ] The node download counter should now have a total of file downloads of 2
- [ ] Delete media 2
- [ ] The node download counter should now have a total of file downloads of 1

### Remarks

For now the file download counter is not displayed and it's only provided in the build array of the entities.

### Notes

- [x] We should merge after #518 get merged.

2021-08-31 14:59 UTC, korhankale commented on lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
> +    catch (\Exception $e) {
I don't really get the point of catching the exception to throw it after 🤔

2021-09-01 07:17 UTC, 4hardfire commented on lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
> +    catch (\Exception $e) {
@korhankale I am doing it in case a new module wants to override my class. But should I return nothing instead?

2021-09-02 10:21 UTC, lramarojaona requested changes

2021-09-02 10:21 UTC, lramarojaona commented on lib/modules/eic_media/modules/eic_media_statistics/src/Access/MediaFileDownloadAccessCheck.php
> +    // Allow access if the user is not a power user.
@4hardfire , small typo here => Allow access if the user is a power user

2021-09-02 10:21 UTC, lramarojaona commented on lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
> +          // We discard the thumbnail field.
@4hardfire , is this needed?
The EntityFileDownlaodCount is quite generic, I don't see a reason to introduce custom logic here?

2021-09-02 10:21 UTC, lramarojaona commented on lib/modules/eic_media/modules/eic_media_statistics/src/EventSubscriber/MediaDownloadRouteSubscriber.php
> +      if (strpos($route->getPath(), '/media/{media}/download') === 0) {
@4hardfire , I think you don't need to loop through all route, you can just get the one you need `media_entity_download.download`
See https://www.drupal.org/docs/drupal-apis/routing-system/altering-existing-routes-and-adding-new-routes-based-on-dynamic-ones

2021-09-02 12:01 UTC, 4hardfire commented on lib/modules/eic_media/modules/eic_media_statistics/src/Access/MediaFileDownloadAccessCheck.php
> +    // Allow access if the user is not a power user.
Fixed.

2021-09-02 12:12 UTC, 4hardfire commented on lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
> +          // We discard the thumbnail field.
Also, this method might fail if we have multiple file fields (not media fields) attached to an entity.

2021-09-02 16:05 UTC, lramarojaona commented on lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
> +          // We discard the thumbnail field.
@4hardfire 
Ok, I fixed it, now it will handle multiple file/image fields.

Can you improve just a bit your comment about the thumbnail as discussed?

Thanks!

2021-09-06 10:29 UTC, lramarojaona commented on lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
> +    catch (\Exception $e) {
@4hardfire , @korhankale ,
What's the status on this?

2021-09-06 12:05 UTC, korhankale commented on lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
> +    catch (\Exception $e) {
Hi
I'd say method/class overriding doesn't have to do anything here, the exception is still "forwarded" after being catched. Generally what should be done is either we stop the execution (e.g: we don't catch the exception) or we catch it, log and return/redirect something/somewhere (especially in controller classes since they are meant to respond to a route after a user request).

In this case $response won't be defined if we let the process continue (and seems like we need it). So we don't need to catch the exception (unless we want to display something custom)

2021-09-06 12:11 UTC, Dromadoros commented on lib/modules/eic_media/modules/eic_media_statistics/src/Controller/MediaFileDownloadController.php
> +    catch (\Exception $e) {
We can remove this try & catch, if you want to throw the error, just let it naturally done by calling the function

2021-09-09 08:59 UTC, 4hardfire commented on lib/modules/eic_media/modules/eic_media_statistics/src/EntityFileDownloadCount.php
> +          // We discard the thumbnail field.
Done.

2021-09-09 09:04 UTC, korhankale approved these changes

2021-09-09 09:17 UTC, merged