EICNET-1371: Fix group file statistics for group content Gallery
EIC-EA/EIC-community-D8 pull request #592
Opened 2021-09-10 08:51 UTC by 4hardfire

2021-09-13 13:54 UTC, lramarojaona requested changes

2021-09-13 13:54 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
> + */
Can we have relevant info here, or at least remove copy/paste text?

2021-09-13 13:54 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
> +   * @usage eic_group_statistics:updateGroupStatistics
I'd suggest to group all our commands under "eic" namespace so we can see them all in once:
`@usage eic:updateGroupStatistics`

2021-09-13 15:50 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
> + */
Done.

2021-09-13 15:51 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
> +   * @command eic_group_statistics:updateGroupStatistics
Done.

2021-09-13 15:51 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
> +   * @usage eic_group_statistics:updateGroupStatistics
Done.

2021-09-13 15:56 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
> +
I did it this way because not every field should be taken into account such as banner images. Maybe we can provide this list using a static method what do you think?

2021-09-13 16:03 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
> +
Mmm, then yes indeed, a specific method/constant(s) would then be nice so we can manage that in a single place

2021-09-13 16:03 UTC, lramarojaona commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
> +
Or maybe exclude specifif fields so that new ones are included by default

2021-09-14 07:22 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
> +
For now I created a static method with the list of fields to use for counting file statistics. I could do the other way around but that requires some time to test and I am not sure if I will be able to work on EIC for the next 2 days.

2021-09-14 09:44 UTC, 4hardfire commented on lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
> +
I added also conditions to ignore fields that does not exist in the node type when calculating the group file statistics.

2021-09-16 09:01 UTC, lramarojaona approved these changes

2021-09-16 12:40 UTC, merged