[EICNET-798]fix: site_admin should also see content with community restriction
EIC-EA/EIC-community-D8 pull request #602
Opened 2021-09-14 11:49 UTC by Dromadoros

How to test:

- [ ] Check if you are site_admin role (not trusted user just)
- [ ] In search for content locked for community, a site_admin should be able to see it

2021-09-14 12:01 UTC, korhankale approved these changes

2021-09-20 10:52 UTC, lramarojaona requested changes

2021-09-20 10:52 UTC, lramarojaona commented on lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
> +    if (!$user->isAnonymous() && ($user->hasRole('trusted_user') || $user->hasRole('site_admin'))) {
@Dromadoros ,
You should always use the defined constants for the roles:
https://github.com/EIC-EA/EIC-community-D8/blob/develop/lib/modules/eic_user/src/UserHelper.php#L48

Also in this case, I guess SA/SCM should be able to see restricted groups, I suggest that you use this method:
https://github.com/EIC-EA/EIC-community-D8/blob/develop/lib/modules/eic_user/src/UserHelper.php#L130

2021-09-21 07:27 UTC, Dromadoros commented on lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
> +    if (!$user->isAnonymous() && ($user->hasRole('trusted_user') || $user->hasRole('site_admin'))) {
Forgot to use constants, you're also right with the function, bedankt

2021-09-21 09:20 UTC, lramarojaona commented on lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
> +    if (!$user->isAnonymous() && ($user->hasRole('trusted_user') || $user->hasRole('site_admin'))) {
Then I guess you can just do
```
if (!$user->isAnonymous() && ($user->hasRole(UserHelper::ROLE_TRUSTED_USER) || UserHelper::isPowerUser($this->getCurrentUser()))) {
```
cause `UserHelper::ROLE_SITE_ADMINISTRATOR` is already included in `UserHelper::isPowerUser()` ;)

2021-09-22 09:09 UTC, merged