EICNET-962: As a GO I want to choose a URL alias for my group (rework)
EIC-EA/EIC-community-D8 pull request #614
Opened 2021-09-16 14:10 UTC by 4hardfire

### Improvements

- Queue group content URL aliases to be updated when a group (with manual URL alias) has changed URL.

### Tests

- [ ] Create a new group and publish it
- [ ] Create a discussion in the group
- [ ] Edit the group, enable manual URL alias and change the URL to a different one
- [ ] Save the group and check if you get redirected to the new URL when navigating to the old one
- [ ] Run cron
- [ ] Check if the discussion URL has been updated according to the new group URL and make sure you get redirected to this new URL when navigating to the old one

2021-09-17 07:43 UTC, Dromadoros commented on lib/modules/eic_groups/eic_groups.module
> +  if (!$entity->get('path')->pathauto) {
we can just put in the same "if" statement

2021-09-20 14:40 UTC, lramarojaona requested changes

2021-09-20 14:40 UTC, lramarojaona commented on lib/modules/eic_groups/eic_groups.module
> +  if (!$entity->get('path')->pathauto) {
@4hardfire , We don't need this check.
When you revert back to pathauto, it will also change the URL alias, so we need this code to run in any case (in case alias has changed)

2021-09-20 16:59 UTC, 4hardfire commented on lib/modules/eic_groups/eic_groups.module
> +  if (!$entity->get('path')->pathauto) {
If the URL alias is set to manual it won't trigger pathauto alias alter hook and for that reason we need this condition otherwise group content aliases won't get updated.

2021-09-21 13:00 UTC, lramarojaona approved these changes

2021-09-21 13:06 UTC, merged