Bugfix/eicnet 971 make story author not linkable
EIC-EA/EIC-community-D8 pull request #623
Opened 2021-09-21 10:13 UTC by xwero

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-971?focusedCommentId=4948934&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4948934

The other comments in the ticket are not actionable.

2021-09-21 15:56 UTC, lramarojaona requested changes

2021-09-21 15:58 UTC, lramarojaona commented on lib/themes/eic_community/includes/preprocess/layout/page.inc
> +          '#path' => $variables['logged_in'] ? $author['path'] : '',
Or just check the 'access user profiles' permission against current user if the function doesn't fit well in here.

2021-09-22 06:51 UTC, xwero commented on lib/themes/eic_community/includes/preprocess/layout/page.inc
> +          '#path' => $variables['logged_in'] ? $author['path'] : '',
Bernardo changed the eic_community_get_teaser_user_display function to use the access method of the Url object. So i need to rewrite this.

2021-09-22 09:02 UTC, xwero commented on lib/themes/eic_community/includes/preprocess/layout/page.inc
> +          '#path' => $variables['logged_in'] ? $author['path'] : '',
The code is updated now.

2021-09-22 09:10 UTC, lramarojaona commented on lib/themes/eic_community/includes/preprocess/layout/page.inc
> +          '#path' => $variables['logged_in'] ? $author['path'] : '',
Cool! :)

2021-09-22 09:10 UTC, lramarojaona approved these changes

2021-09-22 10:53 UTC, merged