EICNET-1485: Implement message_subscribe module for sending message subscriptions
EIC-EA/EIC-community-D8 pull request #680
Opened 2021-10-04 09:04 UTC by 4hardfire

### Features

- Install message_subscribe module and apply patch to prevent infinite loop when sending message notifications (see https://www.drupal.org/project/message_subscribe/issues/3086125);
- Improve EIC Flags helper service in order to exclude anonymous users when retrieving list of flagging entities;
- Switch from custom implementation of message subscription notifications to message_subscribe contrib module and implement hook_message_subscribe_get_subscribers().

### Tests

- [x] Create a new public group and publish it
- [x] As TU, follow the group
- [x] As GO/GA, add new discussion and check the option to "Send notification"
- [x] Run cron
- [x] Check if the TU received an email notification (SUBSCRIPTION :: MT18)
- [x] As GO/GA, edit the discussion and check the option to "Send notification"
- [x] As TU, follow the discussion node
- [x] Run cron
- [x] Check if the TU received an email notification (SUBSCRIPTION :: MT20)
- [x] As GO/GA, add a new comment in the discussion
- [x] Run cron
- [x] Check if the TU received an email notification (SUBSCRIPTION :: MT19)
- [x] As GO/GA, add a new comment reply in the discussion
- [x] Run cron
- [x] Check if the TU received an email notification (SUBSCRIPTION :: MT16)
- [x] As GO/GA, add new discussion (make sure you are following the discussion)
- [x] As TU, recommend the discussion
- [x] Run cron
- [x] Check if the GO/GA received an email notification (SUBSCRIPTION :: MT17)

2021-10-06 09:21 UTC, lramarojaona requested changes
@4hardfire ,
There are some blocking issues that need to be fixed before I continue the review, could you check?

Thank you!

2021-10-06 09:21 UTC, lramarojaona commented on lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module
> +    ->entityFormAlter($message, $subscribe_options = [], $context = []);
This is throwing an error, I guess it should be `messageSubscribeGetSubscribers()`.
Once I change it, I then have a SQL error because of an empty condition:
```
SELECT DISTINCT "fc"."uid" AS "uid"
FROM
"flagging" "fc"
INNER JOIN "users_field_data" "users" ON users.uid = fc.uid
WHERE () AND ("fc"."uid" > :db_condition_placeholder_0) AND ("users"."status" = :db_condition_placeholder_1)
ORDER BY "fc"."uid" ASC
```

2021-10-06 09:21 UTC, lramarojaona commented on lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/MessageSubscribeOperations.php
> +        $subscribers = $this->getSubscribedUsers($node);
My IDE is complaining about this, cause it's the exact same code as `MessageSubscriptionTypes::GROUP_CONTENT_UPDATED` and they could probably be grouped.

2021-10-06 09:21 UTC, lramarojaona commented on lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/MessageSubscribeOperations.php
> +   *   An array, keyed by recipeint user ID, of delivery candidate objects.
Small typo here `recipeint` => `recipient`

2021-10-06 14:47 UTC, 4hardfire commented on lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/MessageSubscribeOperations.php
> +   *   An array, keyed by recipeint user ID, of delivery candidate objects.
Done!

2021-10-11 14:20 UTC, lramarojaona approved these changes

2021-10-11 14:27 UTC, merged