Feature/eicnet 1416 anti spam threshold
EIC-EA/EIC-community-D8 pull request #704
Opened 2021-10-12 11:23 UTC by lramarojaona

### Tests

- [ ] Create a Discussion
- [ ] Check "Post message in the activity stream" and "Send notification"
- [ ] Uncheck "Published" and save
- [ ] Check that no "STREAM :: MT29 :: Discussion insert/update" and "SUBSCRIPTION :: MT18 :: New group content published" messages have been created
- [ ] Update the discussion
- [ ] Check "Post message in the activity stream" and "Send notification"
- [ ] Check "Published" and save
- [ ] Check that "STREAM :: MT29 :: Discussion insert/update" and "SUBSCRIPTION :: MT20 :: Group content updated" have been created created
- [ ] Update the discussion
- [ ] Check "Post message in the activity stream" and "Send notification"
- [ ] Check "Published" and save
- [ ] Check that no new message have been created
- [ ] Run `drush cset eic_messages.settings notification_duplicate_threshold 60`
- [ ] Wait for a minute
- [ ] Update the discussion
- [ ] Check "Post message in the activity stream" and "Send notification"
- [ ] Check "Published" and save
- [ ] Check that "STREAM :: MT29 :: Discussion insert/update" and "SUBSCRIPTION :: MT20 :: Group content updated" have been created created

### Remarks

- To check if messages have been created, you can check `/admin/content/message`
- The default time threshold is 2 hours, so you can lower it to 1 minute for testing purposes

2021-10-15 08:49 UTC, 4hardfire requested changes

2021-10-15 08:49 UTC, 4hardfire commented on lib/modules/eic_messages/src/Service/MessageCreatorBase.php
>        $container->get('entity_type.manager'),
@lramarojaona You're missing a service here `$container->get('config.factory')`.

2021-10-15 10:16 UTC, lramarojaona commented on lib/modules/eic_messages/src/Service/MessageCreatorBase.php
>        $container->get('entity_type.manager'),
This has been fixed

2021-10-18 11:19 UTC, 4hardfire approved these changes
Seems ok to me!

**Quick note**: I found an issue when posting a comment but apparently it got fixed in this commit c0c8cde986aee7d49b39cf35dbf32ca0120db077. I tested with the fix and it worked fine.

2021-10-18 12:21 UTC, merged