[EICNET-1683] add share icon in group flags
EIC-EA/EIC-community-D8 pull request #889
Opened 2021-11-19 10:19 UTC by Askerx9

### before
![image](https://user-images.githubusercontent.com/15520511/142606477-9dd48200-e626-461c-aabd-1365c9aa58f1.png)

### new
![image](https://user-images.githubusercontent.com/15520511/142606348-15ebdd96-d606-4b71-9b0f-4e8b53c51017.png)

2021-11-19 16:10 UTC, filipvt1 requested changes
It is strange that you can't click on the icon to share. Can you check if it is possible to remove the icon from the html and add it with some extra css on the "a" tag that is added by the javascript library?

2021-11-19 16:35 UTC, Askerx9 commented
@filipvt1 not possible because the "a" tag is create by a plugin un js. I can try to add an "onClick" attribute with a JS redirection on the svg but it's ugly

2021-11-23 10:49 UTC, Askerx9 commented
@filipvt1 I checked again and it is not possible to do the onClick on the svg so we have to keep it that way.

2021-11-24 08:23 UTC, filipvt1 approved these changes

2021-11-24 08:53 UTC, merged