[EICNET-1719]chore: Refactor the way we get global overview page
EIC-EA/EIC-community-D8 pull request #890
Opened 2021-11-19 14:30 UTC by Dromadoros

Now we get overview page by an ID directly linked to the entity via the new field "field_overview_id"

2021-11-19 15:28 UTC, 4hardfire requested changes

2021-11-19 15:28 UTC, 4hardfire commented on lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
> +  $back_url = GlobalOverviewPages::getGlobalOverviewPageUrl(GlobalOverviewPages::GROUPS);
I think you still need to change the parameter type in `getGlobalOverviewPageUrl` so that it accepts an integer instead of a string right?

2021-11-19 15:31 UTC, Dromadoros commented on lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
> +  $back_url = GlobalOverviewPages::getGlobalOverviewPageUrl(GlobalOverviewPages::GROUPS);
Yes right, it was working because autoconvert the int to string

2021-11-19 15:42 UTC, 4hardfire approved these changes
Seems ok to me! Do not forget to update overview pages in QA 😄

2021-11-19 15:43 UTC, merged

2021-11-22 10:23 UTC, korhankale commented
@Dromadoros @4hardfire is it really a good idea to use id to retrieve overview pages? Shouldn't we use the source type with/or any other field which helps identifying the queried overview? <br> This approach isn't a robust one according to me (run the fixtures locally twice and you'll get a 500 on every group pages)