Feature/eicnet 1715 topics overview page
EIC-EA/EIC-community-D8 pull request #892
Opened 2021-11-19 16:26 UTC by lramarojaona

### Tests

- [ ] Go to the /topics page
- [ ] Check that you have one view of terms for each top level term

### Remarks

- FE and taxonomy teaser will be part of other tickets

2021-11-23 14:21 UTC, 4hardfire requested changes
I have an error when trying to access `/topics/horizontal`:
`Error: Call to a member function get() on null in eic_topics_preprocess_page__taxonomy__term() (line 18 of /var/www/html/lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc)`

2021-11-23 14:26 UTC, 4hardfire requested changes

2021-11-23 14:26 UTC, 4hardfire commented on lib/modules/eic_overviews/src/Controller/TaxonomyOverviewController.php
> +   * The entity_type.manager service.
Usually I type `The Entity type manager service` instead of `The entity_type.manager service`. Because the service machine name can suffer some changes in the future and in that case it will not make sense anymore.

2021-11-23 14:44 UTC, lramarojaona commented on lib/modules/eic_overviews/src/Controller/TaxonomyOverviewController.php
> +   * The entity_type.manager service.
Mmm, I've seen this example somewhere, but I can change it, I checked examples in core and indeed they don't use the machine name to explain

2021-11-23 15:13 UTC, 4hardfire approved these changes
Seems fine to me!

2021-11-24 09:09 UTC, lramarojaona commented
> I have an error when trying to access `/topics/horizontal`: `Error: Call to a member function get() on null in eic_topics_preprocess_page__taxonomy__term() (line 18 of /var/www/html/lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc)`

Yes, this has been fixed now

2021-11-24 09:21 UTC, merged