EICNET-1510: Email notification for a group transitioned to unblocked
EIC-EA/EIC-community-D8 pull request #924
Opened 2021-11-25 10:26 UTC by 4hardfire

### Features

- Create new generic message type to use when an entity has changed status;
- Send notification message to group owner when SA/SCM unblocks a group.

### Tests

- [ ] As SA/SCM, block a group
- [ ] After blocking the group, go to the group edit form and published the group
- [ ] Run cron
- [ ] Make sure an email notification has been sent to the group owner

2021-11-25 14:38 UTC, lramarojaona requested changes

2021-11-25 14:38 UTC, lramarojaona commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +          : $entity->getEntityTypeId());
You should be able to get the labels easily with something like:
`$entity->type->entity->label()`
instead of harcoding names that we already have in the DB.

I guess you should first test if there is a type.

2021-11-25 14:38 UTC, lramarojaona commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +    if ($entity->getEntityTypeId() === 'group') {
Maybe put this (all this code block) in a separate function?

We may need to sned out notifications for other entity types, and this function is already quite big.

2021-11-25 14:39 UTC, lramarojaona commented
Works well, please check comments ;)

2021-11-26 11:33 UTC, 4hardfire commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +    if ($entity->getEntityTypeId() === 'group') {
Done!

2021-11-26 11:33 UTC, 4hardfire commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +          : $entity->getEntityTypeId());
Done!

2021-11-26 14:12 UTC, lramarojaona commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +  const ENTITY_TYPE_LABELS = [
I guess we can now get rid of this?

2021-11-26 14:18 UTC, lramarojaona approved these changes

2021-11-26 14:18 UTC, lramarojaona commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +          : $entity->getEntityTypeId());
Great!

2021-11-26 14:18 UTC, merged

2021-11-26 14:19 UTC, lramarojaona commented on lib/modules/eic_messages/src/Hooks/EntityOperations.php
> +  const ENTITY_TYPE_LABELS = [
It's now done