[EICNET] correct style for pagination
EIC-EA/EIC-community-D8 pull request #930
Opened 2021-11-25 16:45 UTC by Askerx9

https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=2880%3A18204
http://localhost:8080/groups

2021-11-29 13:49 UTC, filipvt1 requested changes
The styling of the inactive item (regular state, hover state and focus state) isn't correct yet.
![image](https://user-images.githubusercontent.com/86473669/143879443-185236d2-544b-4734-899e-4d982040f7cf.png)
Also check styling on hover of next/prev arrows.

2021-11-29 15:24 UTC, filipvt1 requested changes
The current item is currently shown in a blue text, it should be black. Probably caused by the link inside the active item. In storybook it isn't clickable. This is part of the library used for pagination I guess so I would just update the styling so an active link is styled in black.

2021-11-30 09:28 UTC, Askerx9 commented
it's done and now it's not clickable @filipvt1

2021-12-01 08:09 UTC, filipvt1 approved these changes

2021-12-01 15:22 UTC, merged