[EICNET] rework style of the comments modal
EIC-EA/EIC-community-D8 pull request #934
Opened 2021-11-26 10:32 UTC by Askerx9

### What I did

- [ ] Refactor the code to reuse components for each comments modal
- [ ] Apply a correct style

2021-11-29 08:53 UTC, Dromadoros commented on lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/PopupRequest.js
> +    console.log(this.props.reason);
we can remove this, I know that was my fault

2021-11-30 16:27 UTC, filipvt1 requested changes
Whenever I open the "Edit comment" dialog the focus is on the user profile picture. It would be more logical to have the focus on the input field. For delete and archival the focus is correct so should only be updated for "edit" action. All other things look good. 
Don't know if it is an option to make the user not clickable. That would make the next focus-able item the input field. Otherwise you'll have to implement some custom logic.

2021-12-01 15:22 UTC, Askerx9 commented
@filipvt1  not possible for the moment in this version we can't disable autofocus on the first element, maybe in the next version of the plugin https://github.com/yjose/reactjs-popup/issues/278

2021-12-02 11:19 UTC, Askerx9 commented
@filipvt1 
I have made some changes to this:

- TaggedUser are implemented
- TaggedUser have a good design
- TaggedUsers can be tagged on the children of comments
- Some corrections on the css

2021-12-09 08:19 UTC, filipvt1 approved these changes

2021-12-09 08:46 UTC, merged