[EICNET]feat: Add tagging user system on comment
EIC-EA/EIC-community-D8 pull request #941
Opened 2021-11-29 08:48 UTC by Dromadoros

2021-11-29 13:48 UTC, lramarojaona requested changes
It works althoug the modal window doesn't seem complete to me (it's showing a test message + showing an author, is this needed?)

I added a comment in the ticket regarding emails, cause to me it seems useless if tagged users don't get an email, but it's maybe not in the scope of this ticket

2021-11-29 13:48 UTC, lramarojaona commented on lib/modules/eic_groups/src/Controller/DiscussionController.php
> +      'field_tagged_users' => array_map(function($tagged_user) {
This variable isn't set anywhere `$tagged_user`. I guess this should be `$tagged_users`?

2021-11-29 13:48 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
> +                        <div className="header">{"test"}</div>
This shouldn't be here I guess

2021-11-29 13:48 UTC, lramarojaona commented on lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
> +                                    <a href="?path=user-john-doe"
Do we need to show an author here?

2021-11-29 14:04 UTC, Dromadoros commented on lib/modules/eic_groups/src/Controller/DiscussionController.php
> +      'field_tagged_users' => array_map(function($tagged_user) {
It's an array_map so it's coming from tagged_users (second param of array_map)

2021-11-29 16:08 UTC, Dromadoros commented
> It works althoug the modal window doesn't seem complete to me (it's showing a test message + showing an author, is this needed?)
> 
> I added a comment in the ticket regarding emails, cause to me it seems useless if tagged users don't get an email, but it's maybe not in the scope of this ticket

I removed the author + test title. And I agree, we can see the email point in a discussion/ticket

2021-12-01 10:17 UTC, lramarojaona approved these changes

2021-12-01 10:46 UTC, merged