[EICNET] correct design for Organisation overview in storybook
EIC-EA/EIC-community-D8 pull request #967
Opened 2021-12-03 13:09 UTC by Askerx9

### Links
- overview: http://localhost:9000/?path=/story/bundles-organisation--overview
- teaser: http://localhost:9000/?path=/story/compositions-teaser--organisation-teaser

### Ticket
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=planning&selectedIssue=EICNET-1790&issueLimit=100

2021-12-09 08:56 UTC, filipvt1 requested changes
- The member count is aligned to the left in the designs
- Adding the "ecl-teaser--as-card-white" class to the teaser adds an extra padding on "ecl-teaser__main-wrapper". This causes styling issues with the organization block. Easiest solution might be to remove top and bottom padding specifically for the organisation teaser.

2021-12-15 10:04 UTC, filipvt1 requested changes
In the designs, the member count is located underneath the text. I would add a bottom padding on the organisation teaser.
![image](https://user-images.githubusercontent.com/86473669/146166014-c49e206b-6370-4eb5-8d79-9f116d387c1b.png)

2021-12-15 10:21 UTC, Askerx9 commented
done @filipvt1

2021-12-16 08:25 UTC, filipvt1 approved these changes

2021-12-16 08:35 UTC, merged