Feature/eicnet groups responsive
EIC-EA/EIC-community-D8 pull request #971
Opened 2021-12-06 15:02 UTC by Askerx9

###  What I did

- [ ] Add btn ton expended the filter on mobile
- [ ] change the pagination on mobile phones to have the same as the storybook

2021-12-09 12:38 UTC, filipvt1 requested changes

2021-12-09 12:38 UTC, filipvt1 commented on lib/themes/eic_community/patterns/compositions/subnavigation.html.twig
> +                path: '/themes/custom/eic_community/dist/images/sprite/custom/sprites/custom.svg',
Icon file path should be passed by context, this is different in storybook and Drupal. That's why in storybook we pass along the icon_file_path variable.

2021-12-13 09:13 UTC, Askerx9 commented
@filipvt1 Back-end work on it

2021-12-15 10:23 UTC, filipvt1 approved these changes

2021-12-15 11:16 UTC, merged