[EICNET-358] feat: Introduce the global contact form
EIC-EA/EIC-community-D8 pull request #978
Opened 2021-12-07 18:13 UTC by korhankale

## To Test

- [ ] Run `make setup` to reload fixtures and blocks
- [ ] Log in as a trusted user and go to /contact
- [ ] You should see the contact form with a banner and intro text containing the first name and last name
- [ ] Go to the same page as anonymous
- [ ] You should see the same page with a different intro text

2021-12-09 16:03 UTC, lramarojaona requested changes

2021-12-09 16:03 UTC, lramarojaona commented on config/sync/contact.form.contact_form.yml
> +recipients: []
I had an error becuase no recipient was mentioned, maybe we sould add a default address?
no-reply@example.com

2021-12-09 16:05 UTC, lramarojaona commented
Also there's an issue with the theme, when I disable JS on my browser I don't see the form (which is normal) but I don't see the message neither in the <noscript> tag, I'll create a ticket for that

2021-12-09 18:17 UTC, korhankale commented on config/sync/contact.form.contact_form.yml
> +message: ''
The message is ignored by config_ignore, free to whoever wants to set a message if needed. Don't think those kind of things should be in config

2021-12-09 18:23 UTC, korhankale commented on lib/themes/eic_community/templates/blocks/block--contact-intro-authenticated.html.twig
> +</div>
What should a "basic" block look like and what should we put in that template? By default it will use the base block template. Maybe going for includes can be a better solution but probably won't decrease the template number

Regarding the preprocessing, I don't think final data formatting/rendering should be handled there, it is a more robust practice to give the data to the template and handle basic rendering there (displaying the name)

2021-12-09 18:24 UTC, korhankale commented on config/sync/contact.form.contact_form.yml
> +recipients: []
Indeed we can put a default one and keep it ignored

2021-12-09 18:25 UTC, korhankale commented on lib/themes/eic_community/templates/blocks/block--contact-banner.html.twig
> +</div>
Applying this template to every banner you mean? Currently those banners are only used on overview pages and handled by react. This is the only one outside of it I think

2021-12-10 09:07 UTC, lramarojaona commented on lib/themes/eic_community/templates/blocks/block--contact-banner.html.twig
> +</div>
Yes, there is another one for the homepage.

If this template is how a banner should be displayed (and I believe it is the case), then we should apply it to all banners and not only one specific banner.

2021-12-10 09:18 UTC, lramarojaona commented on lib/themes/eic_community/templates/blocks/block--contact-intro-authenticated.html.twig
> +</div>
Ok, agree with the preprocessing, this makes this template necessary.

But the purpose of the other is strange to me `lib/themes/eic_community/templates/blocks/block--contact-intro-anonymous.html.twig`
I'll comment there

2022-01-17 19:42 UTC, merged