[EICNET-1820]chore: use static method to generate field entity tree settings
EIC-EA/EIC-community-D8 pull request #997
Opened 2021-12-15 13:40 UTC by Dromadoros

2022-01-10 10:24 UTC, lramarojaona requested changes

2022-01-10 10:24 UTC, lramarojaona commented on lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
> +    string $base_url_search_children,
@Dromadoros , 
Is it worth to re-add this? It's not being used.

2022-01-10 10:25 UTC, lramarojaona commented
@Dromadoros , Could you also provide a working example in a README file as how to use this form element in a custom form?
Just tried a bit, but I'm getting the following error:

`InvalidArgumentException: The #default_value property has to be an entity object or an array of entity objects. in Drupal\Core\Entity\Element\EntityAutocomplete::valueCallback() (line 114 of core/lib/Drupal/Core/Entity/Element/EntityAutocomplete.php). `

Thanks!

2022-03-15 18:09 UTC, lenglebert commented
What's the status on this PR? @Dromadoros

2022-03-22 09:47 UTC, closed without merging